BEGIN;

DROP TABLE IF EXISTS audit_log;
DROP TABLE IF EXISTS repositories;
DROP TABLE IF EXISTS project_members;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS tenants;
DROP TABLE IF EXISTS auth_identities;
DROP TABLE IF EXISTS users;

DROP FUNCTION IF EXISTS set_updated_at();

COMMIT;
