// Package store is the Postgres data-access layer. It wraps a pgx connection
// pool and the sqlc-generated typed queries (internal/store/db), and runs schema
// migrations on startup.
package store

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/nielsuitterdijk22/quill/internal/store/db"
)

// Store holds the connection pool and embeds the generated *db.Queries so callers
// can use typed queries directly (store.GetUserByID, store.CreateRepository, ...).
type Store struct {
	pool *pgxpool.Pool
	*db.Queries
}

// New opens a pgx pool against dsn and verifies connectivity.
func New(ctx context.Context, dsn string) (*Store, error) {
	pool, err := pgxpool.New(ctx, dsn)
	if err != nil {
		return nil, fmt.Errorf("create pgx pool: %w", err)
	}
	if err := pool.Ping(ctx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("ping database: %w", err)
	}
	return &Store{pool: pool, Queries: db.New(pool)}, nil
}

// Ping checks database connectivity (used by the readiness probe).
func (s *Store) Ping(ctx context.Context) error {
	return s.pool.Ping(ctx)
}

// Close releases the pool.
func (s *Store) Close() {
	s.pool.Close()
}

// Pool exposes the underlying pool for advanced callers.
func (s *Store) Pool() *pgxpool.Pool { return s.pool }

// ListRunsByCommitSHA returns all pipeline runs for a repo at a specific head
// commit SHA, ordered newest-first. Written by hand rather than generated by
// sqlc to avoid a code-generator re-run; the scan order matches CreatePipelineRun.
func (s *Store) ListRunsByCommitSHA(ctx context.Context, repoID uuid.UUID, sha string) ([]db.PipelineRun, error) {
	const q = `
		SELECT r.id, r.pipeline_id, r.run_number, r.status, r.event, r.ref,
		       r.commit_sha, r.triggered_by, r.started_at, r.finished_at,
		       r.created_at, r.updated_at
		FROM pipeline_runs r
		JOIN pipelines p ON p.id = r.pipeline_id
		WHERE p.repo_id = $1 AND r.commit_sha = $2
		ORDER BY r.created_at DESC`
	rows, err := s.pool.Query(ctx, q, repoID, sha)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var runs []db.PipelineRun
	for rows.Next() {
		var r db.PipelineRun
		if err := rows.Scan(
			&r.ID, &r.PipelineID, &r.RunNumber, &r.Status, &r.Event, &r.Ref,
			&r.CommitSha, &r.TriggeredBy, &r.StartedAt, &r.FinishedAt,
			&r.CreatedAt, &r.UpdatedAt,
		); err != nil {
			return nil, err
		}
		runs = append(runs, r)
	}
	return runs, rows.Err()
}

// DeleteUser permanently removes a user record. All dependent rows (auth_identities,
// project_members, git_tokens) are removed via ON DELETE CASCADE.
func (s *Store) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := s.pool.Exec(ctx, `DELETE FROM users WHERE id = $1`, id)
	return err
}

// UpdateUserEmail updates the email address for the given user and returns the
// refreshed record. Written by hand to avoid re-running the sqlc generator.
func (s *Store) UpdateUserEmail(ctx context.Context, id uuid.UUID, email string) (db.User, error) {
	const q = `
		UPDATE users SET email = $2
		WHERE id = $1
		RETURNING id, username, email, display_name, is_admin, is_active,
		          forgejo_user_id, forgejo_username, created_at, updated_at`
	row := s.pool.QueryRow(ctx, q, id, email)
	var u db.User
	err := row.Scan(
		&u.ID, &u.Username, &u.Email, &u.DisplayName,
		&u.IsAdmin, &u.IsActive, &u.ForgejoUserID, &u.ForgejoUsername,
		&u.CreatedAt, &u.UpdatedAt,
	)
	return u, err
}

// SetUserActive sets the is_active flag for the user identified by username.
func (s *Store) SetUserActive(ctx context.Context, username string, active bool) error {
	_, err := s.pool.Exec(ctx,
		`UPDATE users SET is_active = $2 WHERE lower(username) = lower($1)`,
		username, active)
	return err
}

// CancelRun transitions a pipeline run from running/queued to cancelled if it
// hasn't already finished. Written by hand to avoid re-running sqlc.
func (s *Store) CancelRun(ctx context.Context, repoID uuid.UUID, runNumber int64) (bool, error) {
	tag, err := s.pool.Exec(ctx, `
		UPDATE pipeline_runs r
		SET status = 'cancelled', finished_at = now()
		FROM pipelines p
		WHERE r.pipeline_id = p.id
		  AND p.repo_id = $1
		  AND r.run_number = $2
		  AND r.status IN ('running', 'queued')`,
		repoID, runNumber)
	if err != nil {
		return false, err
	}
	return tag.RowsAffected() > 0, nil
}

// GetOrCreateTenantByExternalOrg atomically resolves the Quill tenant for an
// external IdP organisation, creating it if this is the first login from that
// org. Written by hand to avoid a code-generator re-run.
func (s *Store) GetOrCreateTenantByExternalOrg(ctx context.Context, externalOrgID, slug string) (db.Tenant, error) {
	const q = `
		INSERT INTO tenants (slug, name, external_org_id)
		VALUES ($1, $2, $3)
		ON CONFLICT (external_org_id) WHERE external_org_id IS NOT NULL
		DO UPDATE SET updated_at = now()
		RETURNING id, slug, name, external_org_id, created_at, updated_at`
	row := s.pool.QueryRow(ctx, q, slug, slug, externalOrgID)
	var t db.Tenant
	err := row.Scan(&t.ID, &t.Slug, &t.Name, &t.ExternalOrgID, &t.CreatedAt, &t.UpdatedAt)
	if err == nil {
		return t, nil
	}
	// Slug collision with a different tenant — append org ID suffix and retry.
	const q2 = `
		INSERT INTO tenants (slug, name, external_org_id)
		VALUES ($1, $2, $3)
		ON CONFLICT (external_org_id) WHERE external_org_id IS NOT NULL
		DO UPDATE SET updated_at = now()
		RETURNING id, slug, name, external_org_id, created_at, updated_at`
	shortID := externalOrgID
	if len(shortID) > 8 {
		shortID = shortID[len(shortID)-8:]
	}
	fallbackSlug := slug + "-" + shortID
	row = s.pool.QueryRow(ctx, q2, fallbackSlug, slug, externalOrgID)
	err = row.Scan(&t.ID, &t.Slug, &t.Name, &t.ExternalOrgID, &t.CreatedAt, &t.UpdatedAt)
	return t, err
}

// InTx runs fn inside a transaction, committing on success and rolling back on
// error. Use it for operations that must write several tables atomically (e.g.
// creating a project together with its first membership).
func (s *Store) InTx(ctx context.Context, fn func(q *db.Queries) error) error {
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("begin tx: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	if err := fn(s.Queries.WithTx(tx)); err != nil {
		return err
	}
	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("commit tx: %w", err)
	}
	return nil
}
