// Package store is the Postgres data-access layer. It wraps a pgx connection
// pool and the sqlc-generated typed queries (internal/store/db), and runs schema
// migrations on startup.
package store

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/nielsuitterdijk22/quill/internal/store/db"
)

// Store holds the connection pool and embeds the generated *db.Queries so callers
// can use typed queries directly (store.GetUserByID, store.CreateRepository, ...).
type Store struct {
	pool *pgxpool.Pool
	*db.Queries
}

// New opens a pgx pool against dsn and verifies connectivity.
func New(ctx context.Context, dsn string) (*Store, error) {
	pool, err := pgxpool.New(ctx, dsn)
	if err != nil {
		return nil, fmt.Errorf("create pgx pool: %w", err)
	}
	if err := pool.Ping(ctx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("ping database: %w", err)
	}
	return &Store{pool: pool, Queries: db.New(pool)}, nil
}

// Ping checks database connectivity (used by the readiness probe).
func (s *Store) Ping(ctx context.Context) error {
	return s.pool.Ping(ctx)
}

// Close releases the pool.
func (s *Store) Close() {
	s.pool.Close()
}

// Pool exposes the underlying pool for advanced callers.
func (s *Store) Pool() *pgxpool.Pool { return s.pool }

// ListRunsByCommitSHA returns all pipeline runs for a repo at a specific head
// commit SHA, ordered newest-first. Written by hand rather than generated by
// sqlc to avoid a code-generator re-run; the scan order matches CreatePipelineRun.
func (s *Store) ListRunsByCommitSHA(ctx context.Context, repoID uuid.UUID, sha string) ([]db.PipelineRun, error) {
	const q = `
		SELECT r.id, r.pipeline_id, r.run_number, r.status, r.event, r.ref,
		       r.commit_sha, r.triggered_by, r.started_at, r.finished_at,
		       r.created_at, r.updated_at
		FROM pipeline_runs r
		JOIN pipelines p ON p.id = r.pipeline_id
		WHERE p.repo_id = $1 AND r.commit_sha = $2
		ORDER BY r.created_at DESC`
	rows, err := s.pool.Query(ctx, q, repoID, sha)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var runs []db.PipelineRun
	for rows.Next() {
		var r db.PipelineRun
		if err := rows.Scan(
			&r.ID, &r.PipelineID, &r.RunNumber, &r.Status, &r.Event, &r.Ref,
			&r.CommitSha, &r.TriggeredBy, &r.StartedAt, &r.FinishedAt,
			&r.CreatedAt, &r.UpdatedAt,
		); err != nil {
			return nil, err
		}
		runs = append(runs, r)
	}
	return runs, rows.Err()
}

// InTx runs fn inside a transaction, committing on success and rolling back on
// error. Use it for operations that must write several tables atomically (e.g.
// creating a project together with its first membership).
func (s *Store) InTx(ctx context.Context, fn func(q *db.Queries) error) error {
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("begin tx: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	if err := fn(s.Queries.WithTx(tx)); err != nil {
		return err
	}
	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("commit tx: %w", err)
	}
	return nil
}
