// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_log.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditLog = `-- name: InsertAuditLog :one
INSERT INTO audit_log (actor_user_id, action, target_type, target_id, metadata, ip_address, actor_username)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, actor_user_id, action, target_type, target_id, metadata, created_at, ip_address, actor_username
`

type InsertAuditLogParams struct {
	ActorUserID   uuid.NullUUID `json:"actorUserId"`
	Action        string        `json:"action"`
	TargetType    string        `json:"targetType"`
	TargetID      string        `json:"targetId"`
	Metadata      []byte        `json:"metadata"`
	IPAddress     string        `json:"ipAddress"`
	ActorUsername string        `json:"actorUsername"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.ActorUserID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Metadata,
		arg.IPAddress,
		arg.ActorUsername,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.Metadata,
		&i.CreatedAt,
		&i.IPAddress,
		&i.ActorUsername,
	)
	return i, err
}

const listAuditLogFiltered = `-- name: ListAuditLogFiltered :many
SELECT id, actor_user_id, action, target_type, target_id, metadata, created_at, ip_address, actor_username
FROM audit_log
WHERE
  ($1::text = '' OR action LIKE $1 || '%')
  AND ($2::timestamptz IS NULL OR created_at >= $2)
  AND ($3::timestamptz IS NULL OR created_at <= $3)
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListAuditLogFilteredParams struct {
	ActionPrefix string              `json:"actionPrefix"`
	Since        pgtype.Timestamptz  `json:"since"`
	Until        pgtype.Timestamptz  `json:"until"`
	Limit        int32               `json:"limit"`
	Offset       int32               `json:"offset"`
}

func (q *Queries) ListAuditLogFiltered(ctx context.Context, arg ListAuditLogFilteredParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogFiltered,
		arg.ActionPrefix,
		arg.Since,
		arg.Until,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Metadata,
			&i.CreatedAt,
			&i.IPAddress,
			&i.ActorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAuditLogFiltered = `-- name: CountAuditLogFiltered :one
SELECT count(*)
FROM audit_log
WHERE
  ($1::text = '' OR action LIKE $1 || '%')
  AND ($2::timestamptz IS NULL OR created_at >= $2)
  AND ($3::timestamptz IS NULL OR created_at <= $3)
`

type CountAuditLogFilteredParams struct {
	ActionPrefix string             `json:"actionPrefix"`
	Since        pgtype.Timestamptz `json:"since"`
	Until        pgtype.Timestamptz `json:"until"`
}

func (q *Queries) CountAuditLogFiltered(ctx context.Context, arg CountAuditLogFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogFiltered,
		arg.ActionPrefix,
		arg.Since,
		arg.Until,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

// ensure time import is used
var _ = time.Time{}
