// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_identities.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthIdentity = `-- name: CreateAuthIdentity :one
INSERT INTO auth_identities (user_id, provider, subject, secret_hash)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, provider, subject, secret_hash, created_at, updated_at
`

type CreateAuthIdentityParams struct {
	UserID     uuid.UUID   `json:"userId"`
	Provider   string      `json:"provider"`
	Subject    string      `json:"subject"`
	SecretHash pgtype.Text `json:"secretHash"`
}

func (q *Queries) CreateAuthIdentity(ctx context.Context, arg CreateAuthIdentityParams) (AuthIdentity, error) {
	row := q.db.QueryRow(ctx, createAuthIdentity,
		arg.UserID,
		arg.Provider,
		arg.Subject,
		arg.SecretHash,
	)
	var i AuthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Subject,
		&i.SecretHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthIdentity = `-- name: GetAuthIdentity :one
SELECT id, user_id, provider, subject, secret_hash, created_at, updated_at FROM auth_identities
WHERE provider = $1 AND subject = $2
`

type GetAuthIdentityParams struct {
	Provider string `json:"provider"`
	Subject  string `json:"subject"`
}

func (q *Queries) GetAuthIdentity(ctx context.Context, arg GetAuthIdentityParams) (AuthIdentity, error) {
	row := q.db.QueryRow(ctx, getAuthIdentity, arg.Provider, arg.Subject)
	var i AuthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Subject,
		&i.SecretHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAuthIdentitiesForUser = `-- name: ListAuthIdentitiesForUser :many
SELECT id, user_id, provider, subject, secret_hash, created_at, updated_at FROM auth_identities
WHERE user_id = $1
ORDER BY provider
`

func (q *Queries) ListAuthIdentitiesForUser(ctx context.Context, userID uuid.UUID) ([]AuthIdentity, error) {
	rows, err := q.db.Query(ctx, listAuthIdentitiesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthIdentity{}
	for rows.Next() {
		var i AuthIdentity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.Subject,
			&i.SecretHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAuthIdentitySecret = `-- name: UpdateAuthIdentitySecret :exec
UPDATE auth_identities
SET secret_hash = $2
WHERE id = $1
`

type UpdateAuthIdentitySecretParams struct {
	ID         uuid.UUID   `json:"id"`
	SecretHash pgtype.Text `json:"secretHash"`
}

func (q *Queries) UpdateAuthIdentitySecret(ctx context.Context, arg UpdateAuthIdentitySecretParams) error {
	_, err := q.db.Exec(ctx, updateAuthIdentitySecret, arg.ID, arg.SecretHash)
	return err
}
