// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: branch_policies.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteBranchPolicy = `-- name: DeleteBranchPolicy :execrows
DELETE FROM branch_policies
WHERE repo_id = $1 AND pattern = $2
`

type DeleteBranchPolicyParams struct {
	RepoID  uuid.UUID `json:"repoId"`
	Pattern string    `json:"pattern"`
}

func (q *Queries) DeleteBranchPolicy(ctx context.Context, arg DeleteBranchPolicyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBranchPolicy, arg.RepoID, arg.Pattern)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBranchPolicy = `-- name: GetBranchPolicy :one
SELECT id, repo_id, pattern, required_approvals, dismiss_stale_approvals, require_up_to_date, block_force_push, require_pull_request, created_at, updated_at FROM branch_policies
WHERE repo_id = $1 AND pattern = $2
`

type GetBranchPolicyParams struct {
	RepoID  uuid.UUID `json:"repoId"`
	Pattern string    `json:"pattern"`
}

func (q *Queries) GetBranchPolicy(ctx context.Context, arg GetBranchPolicyParams) (BranchPolicy, error) {
	row := q.db.QueryRow(ctx, getBranchPolicy, arg.RepoID, arg.Pattern)
	var i BranchPolicy
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Pattern,
		&i.RequiredApprovals,
		&i.DismissStaleApprovals,
		&i.RequireUpToDate,
		&i.BlockForcePush,
		&i.RequirePullRequest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBranchPoliciesByRepo = `-- name: ListBranchPoliciesByRepo :many
SELECT id, repo_id, pattern, required_approvals, dismiss_stale_approvals, require_up_to_date, block_force_push, require_pull_request, created_at, updated_at FROM branch_policies
WHERE repo_id = $1
ORDER BY pattern
`

func (q *Queries) ListBranchPoliciesByRepo(ctx context.Context, repoID uuid.UUID) ([]BranchPolicy, error) {
	rows, err := q.db.Query(ctx, listBranchPoliciesByRepo, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BranchPolicy{}
	for rows.Next() {
		var i BranchPolicy
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Pattern,
			&i.RequiredApprovals,
			&i.DismissStaleApprovals,
			&i.RequireUpToDate,
			&i.BlockForcePush,
			&i.RequirePullRequest,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBranchPolicy = `-- name: UpsertBranchPolicy :one
INSERT INTO branch_policies (
  repo_id, pattern, required_approvals, dismiss_stale_approvals,
  require_up_to_date, block_force_push, require_pull_request
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (repo_id, pattern) DO UPDATE SET
  required_approvals      = EXCLUDED.required_approvals,
  dismiss_stale_approvals = EXCLUDED.dismiss_stale_approvals,
  require_up_to_date      = EXCLUDED.require_up_to_date,
  block_force_push        = EXCLUDED.block_force_push,
  require_pull_request    = EXCLUDED.require_pull_request
RETURNING id, repo_id, pattern, required_approvals, dismiss_stale_approvals, require_up_to_date, block_force_push, require_pull_request, created_at, updated_at
`

type UpsertBranchPolicyParams struct {
	RepoID                uuid.UUID `json:"repoId"`
	Pattern               string    `json:"pattern"`
	RequiredApprovals     int32     `json:"requiredApprovals"`
	DismissStaleApprovals bool      `json:"dismissStaleApprovals"`
	RequireUpToDate       bool      `json:"requireUpToDate"`
	BlockForcePush        bool      `json:"blockForcePush"`
	RequirePullRequest    bool      `json:"requirePullRequest"`
}

func (q *Queries) UpsertBranchPolicy(ctx context.Context, arg UpsertBranchPolicyParams) (BranchPolicy, error) {
	row := q.db.QueryRow(ctx, upsertBranchPolicy,
		arg.RepoID,
		arg.Pattern,
		arg.RequiredApprovals,
		arg.DismissStaleApprovals,
		arg.RequireUpToDate,
		arg.BlockForcePush,
		arg.RequirePullRequest,
	)
	var i BranchPolicy
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Pattern,
		&i.RequiredApprovals,
		&i.DismissStaleApprovals,
		&i.RequireUpToDate,
		&i.BlockForcePush,
		&i.RequirePullRequest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
