// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: git_tokens.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createGitToken = `-- name: CreateGitToken :one
INSERT INTO git_tokens (user_id, name, forgejo_token_name)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, forgejo_token_name, created_at
`

type CreateGitTokenParams struct {
	UserID           uuid.UUID `json:"userId"`
	Name             string    `json:"name"`
	ForgejoTokenName string    `json:"forgejoTokenName"`
}

func (q *Queries) CreateGitToken(ctx context.Context, arg CreateGitTokenParams) (GitToken, error) {
	row := q.db.QueryRow(ctx, createGitToken, arg.UserID, arg.Name, arg.ForgejoTokenName)
	var i GitToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ForgejoTokenName,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGitToken = `-- name: DeleteGitToken :exec
DELETE FROM git_tokens
WHERE id = $1 AND user_id = $2
`

type DeleteGitTokenParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"userId"`
}

func (q *Queries) DeleteGitToken(ctx context.Context, arg DeleteGitTokenParams) error {
	_, err := q.db.Exec(ctx, deleteGitToken, arg.ID, arg.UserID)
	return err
}

const getGitToken = `-- name: GetGitToken :one
SELECT id, user_id, name, forgejo_token_name, created_at FROM git_tokens
WHERE id = $1 AND user_id = $2
`

type GetGitTokenParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"userId"`
}

func (q *Queries) GetGitToken(ctx context.Context, arg GetGitTokenParams) (GitToken, error) {
	row := q.db.QueryRow(ctx, getGitToken, arg.ID, arg.UserID)
	var i GitToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ForgejoTokenName,
		&i.CreatedAt,
	)
	return i, err
}

const listGitTokensByUser = `-- name: ListGitTokensByUser :many
SELECT id, user_id, name, forgejo_token_name, created_at FROM git_tokens
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListGitTokensByUser(ctx context.Context, userID uuid.UUID) ([]GitToken, error) {
	rows, err := q.db.Query(ctx, listGitTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GitToken{}
	for rows.Next() {
		var i GitToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.ForgejoTokenName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
