// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID            int64         `json:"id"`
	ActorUserID   uuid.NullUUID `json:"actorUserId"`
	Action        string        `json:"action"`
	TargetType    string        `json:"targetType"`
	TargetID      string        `json:"targetId"`
	Metadata      []byte        `json:"metadata"`
	CreatedAt     time.Time     `json:"createdAt"`
	IPAddress     string        `json:"ipAddress"`
	ActorUsername string        `json:"actorUsername"`
}

type AuthIdentity struct {
	ID         uuid.UUID   `json:"id"`
	UserID     uuid.UUID   `json:"userId"`
	Provider   string      `json:"provider"`
	Subject    string      `json:"subject"`
	SecretHash pgtype.Text `json:"secretHash"`
	CreatedAt  time.Time   `json:"createdAt"`
	UpdatedAt  time.Time   `json:"updatedAt"`
}

type Environment struct {
	ID          uuid.UUID `json:"id"`
	ProjectID   uuid.UUID `json:"projectId"`
	Slug        string    `json:"slug"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Rank        int32     `json:"rank"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type GitToken struct {
	ID               uuid.UUID `json:"id"`
	UserID           uuid.UUID `json:"userId"`
	Name             string    `json:"name"`
	ForgejoTokenName string    `json:"forgejoTokenName"`
	CreatedAt        time.Time `json:"createdAt"`
}

type Pipeline struct {
	ID           uuid.UUID `json:"id"`
	RepoID       uuid.UUID `json:"repoId"`
	WorkflowPath string    `json:"workflowPath"`
	Name         string    `json:"name"`
	CreatedAt    time.Time `json:"createdAt"`
	UpdatedAt    time.Time `json:"updatedAt"`
}

type PipelineJob struct {
	ID         uuid.UUID          `json:"id"`
	RunID      uuid.UUID          `json:"runId"`
	JobKey     string             `json:"jobKey"`
	Name       string             `json:"name"`
	RunsOn     string             `json:"runsOn"`
	Status     string             `json:"status"`
	Position   int32              `json:"position"`
	StartedAt  pgtype.Timestamptz `json:"startedAt"`
	FinishedAt pgtype.Timestamptz `json:"finishedAt"`
	CreatedAt  time.Time          `json:"createdAt"`
	UpdatedAt  time.Time          `json:"updatedAt"`
}

type PipelineRun struct {
	ID          uuid.UUID          `json:"id"`
	PipelineID  uuid.UUID          `json:"pipelineId"`
	RunNumber   int64              `json:"runNumber"`
	Status      string             `json:"status"`
	Event       string             `json:"event"`
	Ref         string             `json:"ref"`
	CommitSha   string             `json:"commitSha"`
	TriggeredBy uuid.NullUUID      `json:"triggeredBy"`
	StartedAt   pgtype.Timestamptz `json:"startedAt"`
	FinishedAt  pgtype.Timestamptz `json:"finishedAt"`
	CreatedAt   time.Time          `json:"createdAt"`
	UpdatedAt   time.Time          `json:"updatedAt"`
}

type PipelineStep struct {
	ID         uuid.UUID          `json:"id"`
	JobID      uuid.UUID          `json:"jobId"`
	Position   int32              `json:"position"`
	Name       string             `json:"name"`
	StepType   string             `json:"stepType"`
	Status     string             `json:"status"`
	Logs       string             `json:"logs"`
	StartedAt  pgtype.Timestamptz `json:"startedAt"`
	FinishedAt pgtype.Timestamptz `json:"finishedAt"`
	CreatedAt  time.Time          `json:"createdAt"`
	UpdatedAt  time.Time          `json:"updatedAt"`
}

type Policy struct {
	ID        uuid.UUID `json:"id"`
	ScopeType string    `json:"scopeType"`
	ScopeID   uuid.UUID `json:"scopeId"`
	Kind      string    `json:"kind"`
	Selector  string    `json:"selector"`
	Rules     []byte    `json:"rules"`
	Locked    bool      `json:"locked"`
	Enabled   bool      `json:"enabled"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type Project struct {
	ID             uuid.UUID   `json:"id"`
	TenantID       uuid.UUID   `json:"tenantId"`
	Slug           string      `json:"slug"`
	Name           string      `json:"name"`
	Description    string      `json:"description"`
	ForgejoOrgName pgtype.Text `json:"forgejoOrgName"`
	IsPersonal     bool        `json:"isPersonal"`
	CreatedAt      time.Time   `json:"createdAt"`
	UpdatedAt      time.Time   `json:"updatedAt"`
}

type ProjectMember struct {
	ProjectID uuid.UUID `json:"projectId"`
	UserID    uuid.UUID `json:"userId"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"createdAt"`
}

type ProjectSyncOutbox struct {
	ID            uuid.UUID          `json:"id"`
	ProjectID     uuid.UUID          `json:"projectId"`
	EventType     string             `json:"eventType"`
	Payload       []byte             `json:"payload"`
	OccurredAt    time.Time          `json:"occurredAt"`
	Attempts      int32              `json:"attempts"`
	NextAttemptAt time.Time          `json:"nextAttemptAt"`
	DeliveredAt   pgtype.Timestamptz `json:"deliveredAt"`
}

type Repository struct {
	ID            uuid.UUID   `json:"id"`
	ProjectID     uuid.UUID   `json:"projectId"`
	Slug          string      `json:"slug"`
	Name          string      `json:"name"`
	Description   string      `json:"description"`
	Visibility    string      `json:"visibility"`
	DefaultBranch string      `json:"defaultBranch"`
	IsArchived    bool        `json:"isArchived"`
	ForgejoRepoID pgtype.Int8 `json:"forgejoRepoId"`
	ForgejoOwner  pgtype.Text `json:"forgejoOwner"`
	ForgejoName   pgtype.Text `json:"forgejoName"`
	CreatedAt     time.Time   `json:"createdAt"`
	UpdatedAt     time.Time   `json:"updatedAt"`
}

type Tenant struct {
	ID         uuid.UUID   `json:"id"`
	Slug       string      `json:"slug"`
	Name       string      `json:"name"`
	ClerkOrgID pgtype.Text `json:"clerkOrgId"`
	CreatedAt  time.Time   `json:"createdAt"`
	UpdatedAt  time.Time   `json:"updatedAt"`
}

type User struct {
	ID              uuid.UUID   `json:"id"`
	Username        string      `json:"username"`
	Email           string      `json:"email"`
	DisplayName     string      `json:"displayName"`
	IsAdmin         bool        `json:"isAdmin"`
	IsActive        bool        `json:"isActive"`
	ForgejoUserID   pgtype.Int8 `json:"forgejoUserId"`
	ForgejoUsername pgtype.Text `json:"forgejoUsername"`
	CreatedAt       time.Time   `json:"createdAt"`
	UpdatedAt       time.Time   `json:"updatedAt"`
}
