// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID          int64         `json:"id"`
	ActorUserID uuid.NullUUID `json:"actorUserId"`
	Action      string        `json:"action"`
	TargetType  string        `json:"targetType"`
	TargetID    string        `json:"targetId"`
	Metadata    []byte        `json:"metadata"`
	CreatedAt   time.Time     `json:"createdAt"`
}

type AuthIdentity struct {
	ID         uuid.UUID   `json:"id"`
	UserID     uuid.UUID   `json:"userId"`
	Provider   string      `json:"provider"`
	Subject    string      `json:"subject"`
	SecretHash pgtype.Text `json:"secretHash"`
	CreatedAt  time.Time   `json:"createdAt"`
	UpdatedAt  time.Time   `json:"updatedAt"`
}

type BranchPolicy struct {
	ID                    uuid.UUID `json:"id"`
	RepoID                uuid.UUID `json:"repoId"`
	Pattern               string    `json:"pattern"`
	RequiredApprovals     int32     `json:"requiredApprovals"`
	DismissStaleApprovals bool      `json:"dismissStaleApprovals"`
	RequireUpToDate       bool      `json:"requireUpToDate"`
	BlockForcePush        bool      `json:"blockForcePush"`
	RequirePullRequest    bool      `json:"requirePullRequest"`
	CreatedAt             time.Time `json:"createdAt"`
	UpdatedAt             time.Time `json:"updatedAt"`
}

type OrgMember struct {
	OrgID     uuid.UUID `json:"orgId"`
	UserID    uuid.UUID `json:"userId"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"createdAt"`
}

type Organization struct {
	ID             uuid.UUID     `json:"id"`
	Slug           string        `json:"slug"`
	Name           string        `json:"name"`
	Description    string        `json:"description"`
	ParentID       uuid.NullUUID `json:"parentId"`
	ForgejoOrgName pgtype.Text   `json:"forgejoOrgName"`
	CreatedAt      time.Time     `json:"createdAt"`
	UpdatedAt      time.Time     `json:"updatedAt"`
}

type Repository struct {
	ID            uuid.UUID   `json:"id"`
	OrgID         uuid.UUID   `json:"orgId"`
	OwningTeamID  uuid.UUID   `json:"owningTeamId"`
	Slug          string      `json:"slug"`
	Name          string      `json:"name"`
	Description   string      `json:"description"`
	Visibility    string      `json:"visibility"`
	DefaultBranch string      `json:"defaultBranch"`
	IsArchived    bool        `json:"isArchived"`
	ForgejoRepoID pgtype.Int8 `json:"forgejoRepoId"`
	ForgejoOwner  pgtype.Text `json:"forgejoOwner"`
	ForgejoName   pgtype.Text `json:"forgejoName"`
	CreatedAt     time.Time   `json:"createdAt"`
	UpdatedAt     time.Time   `json:"updatedAt"`
}

type Team struct {
	ID          uuid.UUID `json:"id"`
	OrgID       uuid.UUID `json:"orgId"`
	Slug        string    `json:"slug"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type TeamMember struct {
	TeamID    uuid.UUID `json:"teamId"`
	UserID    uuid.UUID `json:"userId"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"createdAt"`
}

type User struct {
	ID              uuid.UUID   `json:"id"`
	Username        string      `json:"username"`
	Email           string      `json:"email"`
	DisplayName     string      `json:"displayName"`
	IsAdmin         bool        `json:"isAdmin"`
	IsActive        bool        `json:"isActive"`
	ForgejoUserID   pgtype.Int8 `json:"forgejoUserId"`
	ForgejoUsername pgtype.Text `json:"forgejoUsername"`
	CreatedAt       time.Time   `json:"createdAt"`
	UpdatedAt       time.Time   `json:"updatedAt"`
}
