// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: org_invites.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createInvite = `-- name: CreateInvite :one
INSERT INTO org_invites (tenant_id, email, role, token_hash, invited_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, email, role, token_hash, status, invited_by, accepted_user_id, expires_at, created_at, accepted_at
`

type CreateInviteParams struct {
	TenantID  uuid.UUID     `json:"tenantId"`
	Email     string        `json:"email"`
	Role      string        `json:"role"`
	TokenHash string        `json:"tokenHash"`
	InvitedBy uuid.NullUUID `json:"invitedBy"`
	ExpiresAt time.Time     `json:"expiresAt"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (OrgInvite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.TenantID,
		arg.Email,
		arg.Role,
		arg.TokenHash,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i OrgInvite
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.Status,
		&i.InvitedBy,
		&i.AcceptedUserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.AcceptedAt,
	)
	return i, err
}

const getInviteByTokenHash = `-- name: GetInviteByTokenHash :one
SELECT id, tenant_id, email, role, token_hash, status, invited_by, accepted_user_id, expires_at, created_at, accepted_at
FROM org_invites WHERE token_hash = $1
`

func (q *Queries) GetInviteByTokenHash(ctx context.Context, tokenHash string) (OrgInvite, error) {
	row := q.db.QueryRow(ctx, getInviteByTokenHash, tokenHash)
	var i OrgInvite
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.Status,
		&i.InvitedBy,
		&i.AcceptedUserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.AcceptedAt,
	)
	return i, err
}

const listPendingInvitesByTenant = `-- name: ListPendingInvitesByTenant :many
SELECT id, tenant_id, email, role, token_hash, status, invited_by, accepted_user_id, expires_at, created_at, accepted_at
FROM org_invites
WHERE tenant_id = $1 AND status = 'pending'
ORDER BY created_at DESC
`

func (q *Queries) ListPendingInvitesByTenant(ctx context.Context, tenantID uuid.UUID) ([]OrgInvite, error) {
	rows, err := q.db.Query(ctx, listPendingInvitesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrgInvite{}
	for rows.Next() {
		var i OrgInvite
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Email,
			&i.Role,
			&i.TokenHash,
			&i.Status,
			&i.InvitedBy,
			&i.AcceptedUserID,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.AcceptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeInvite = `-- name: RevokeInvite :execrows
UPDATE org_invites SET status = 'revoked'
WHERE id = $1 AND tenant_id = $2 AND status = 'pending'
`

type RevokeInviteParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenantId"`
}

func (q *Queries) RevokeInvite(ctx context.Context, arg RevokeInviteParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeInvite, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokePendingInvitesByEmail = `-- name: RevokePendingInvitesByEmail :exec
UPDATE org_invites SET status = 'revoked'
WHERE tenant_id = $1 AND lower(email) = lower($2) AND status = 'pending'
`

type RevokePendingInvitesByEmailParams struct {
	TenantID uuid.UUID `json:"tenantId"`
	Email    string    `json:"email"`
}

func (q *Queries) RevokePendingInvitesByEmail(ctx context.Context, arg RevokePendingInvitesByEmailParams) error {
	_, err := q.db.Exec(ctx, revokePendingInvitesByEmail, arg.TenantID, arg.Email)
	return err
}

const markInviteAccepted = `-- name: MarkInviteAccepted :exec
UPDATE org_invites SET status = 'accepted', accepted_user_id = $2, accepted_at = now()
WHERE id = $1
`

type MarkInviteAcceptedParams struct {
	ID             uuid.UUID     `json:"id"`
	AcceptedUserID uuid.NullUUID `json:"acceptedUserId"`
}

func (q *Queries) MarkInviteAccepted(ctx context.Context, arg MarkInviteAcceptedParams) error {
	_, err := q.db.Exec(ctx, markInviteAccepted, arg.ID, arg.AcceptedUserID)
	return err
}
