// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organizations.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countOrganizations = `-- name: CountOrganizations :one
SELECT count(*) FROM organizations
`

func (q *Queries) CountOrganizations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (slug, name, description, parent_id)
VALUES ($1, $2, $3, $4)
RETURNING id, slug, name, description, parent_id, forgejo_org_name, created_at, updated_at
`

type CreateOrganizationParams struct {
	Slug        string        `json:"slug"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	ParentID    uuid.NullUUID `json:"parentId"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.ParentID,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.ParentID,
		&i.ForgejoOrgName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, slug, name, description, parent_id, forgejo_org_name, created_at, updated_at FROM organizations WHERE id = $1
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.ParentID,
		&i.ForgejoOrgName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, slug, name, description, parent_id, forgejo_org_name, created_at, updated_at FROM organizations WHERE lower(slug) = lower($1)
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, lower string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationBySlug, lower)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.ParentID,
		&i.ForgejoOrgName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrganizations = `-- name: ListOrganizations :many
SELECT id, slug, name, description, parent_id, forgejo_org_name, created_at, updated_at FROM organizations
ORDER BY slug
LIMIT $1 OFFSET $2
`

type ListOrganizationsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listOrganizations, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.ParentID,
			&i.ForgejoOrgName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOrganizationForgejoName = `-- name: SetOrganizationForgejoName :one
UPDATE organizations
SET forgejo_org_name = $2
WHERE id = $1
RETURNING id, slug, name, description, parent_id, forgejo_org_name, created_at, updated_at
`

type SetOrganizationForgejoNameParams struct {
	ID             uuid.UUID   `json:"id"`
	ForgejoOrgName pgtype.Text `json:"forgejoOrgName"`
}

func (q *Queries) SetOrganizationForgejoName(ctx context.Context, arg SetOrganizationForgejoNameParams) (Organization, error) {
	row := q.db.QueryRow(ctx, setOrganizationForgejoName, arg.ID, arg.ForgejoOrgName)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.ParentID,
		&i.ForgejoOrgName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
