// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pipeline_secrets.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPipelineSecret = `-- name: CreatePipelineSecret :one
INSERT INTO pipeline_secrets (
  project_id, repo_id, environment_id, name, ciphertext, nonce, created_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, project_id, repo_id, environment_id, name, ciphertext, nonce, created_by, created_at, updated_at
`

type CreatePipelineSecretParams struct {
	ProjectID     uuid.UUID     `json:"projectId"`
	RepoID        uuid.NullUUID `json:"repoId"`
	EnvironmentID uuid.NullUUID `json:"environmentId"`
	Name          string        `json:"name"`
	Ciphertext    []byte        `json:"ciphertext"`
	Nonce         []byte        `json:"nonce"`
	CreatedBy     uuid.NullUUID `json:"createdBy"`
}

func (q *Queries) CreatePipelineSecret(ctx context.Context, arg CreatePipelineSecretParams) (PipelineSecret, error) {
	row := q.db.QueryRow(ctx, createPipelineSecret,
		arg.ProjectID,
		arg.RepoID,
		arg.EnvironmentID,
		arg.Name,
		arg.Ciphertext,
		arg.Nonce,
		arg.CreatedBy,
	)
	var i PipelineSecret
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RepoID,
		&i.EnvironmentID,
		&i.Name,
		&i.Ciphertext,
		&i.Nonce,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePipelineSecret = `-- name: DeletePipelineSecret :exec
DELETE FROM pipeline_secrets WHERE id = $1
`

func (q *Queries) DeletePipelineSecret(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePipelineSecret, id)
	return err
}

const getEnvironmentSecretByName = `-- name: GetEnvironmentSecretByName :one
SELECT id, project_id, repo_id, environment_id, name, ciphertext, nonce, created_by, created_at, updated_at FROM pipeline_secrets
WHERE environment_id = $1 AND name = $2
`

type GetEnvironmentSecretByNameParams struct {
	EnvironmentID uuid.NullUUID `json:"environmentId"`
	Name          string        `json:"name"`
}

func (q *Queries) GetEnvironmentSecretByName(ctx context.Context, arg GetEnvironmentSecretByNameParams) (PipelineSecret, error) {
	row := q.db.QueryRow(ctx, getEnvironmentSecretByName, arg.EnvironmentID, arg.Name)
	var i PipelineSecret
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RepoID,
		&i.EnvironmentID,
		&i.Name,
		&i.Ciphertext,
		&i.Nonce,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectSecretByName = `-- name: GetProjectSecretByName :one
SELECT id, project_id, repo_id, environment_id, name, ciphertext, nonce, created_by, created_at, updated_at FROM pipeline_secrets
WHERE project_id = $1 AND repo_id IS NULL AND environment_id IS NULL AND name = $2
`

type GetProjectSecretByNameParams struct {
	ProjectID uuid.UUID `json:"projectId"`
	Name      string    `json:"name"`
}

func (q *Queries) GetProjectSecretByName(ctx context.Context, arg GetProjectSecretByNameParams) (PipelineSecret, error) {
	row := q.db.QueryRow(ctx, getProjectSecretByName, arg.ProjectID, arg.Name)
	var i PipelineSecret
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RepoID,
		&i.EnvironmentID,
		&i.Name,
		&i.Ciphertext,
		&i.Nonce,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepoSecretByName = `-- name: GetRepoSecretByName :one
SELECT id, project_id, repo_id, environment_id, name, ciphertext, nonce, created_by, created_at, updated_at FROM pipeline_secrets
WHERE repo_id = $1 AND name = $2
`

type GetRepoSecretByNameParams struct {
	RepoID uuid.NullUUID `json:"repoId"`
	Name   string        `json:"name"`
}

func (q *Queries) GetRepoSecretByName(ctx context.Context, arg GetRepoSecretByNameParams) (PipelineSecret, error) {
	row := q.db.QueryRow(ctx, getRepoSecretByName, arg.RepoID, arg.Name)
	var i PipelineSecret
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RepoID,
		&i.EnvironmentID,
		&i.Name,
		&i.Ciphertext,
		&i.Nonce,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnvironmentSecrets = `-- name: ListEnvironmentSecrets :many
SELECT id, project_id, repo_id, environment_id, name, ciphertext, nonce, created_by, created_at, updated_at FROM pipeline_secrets
WHERE environment_id = $1
ORDER BY name
`

func (q *Queries) ListEnvironmentSecrets(ctx context.Context, environmentID uuid.NullUUID) ([]PipelineSecret, error) {
	rows, err := q.db.Query(ctx, listEnvironmentSecrets, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PipelineSecret{}
	for rows.Next() {
		var i PipelineSecret
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.RepoID,
			&i.EnvironmentID,
			&i.Name,
			&i.Ciphertext,
			&i.Nonce,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectSecrets = `-- name: ListProjectSecrets :many
SELECT id, project_id, repo_id, environment_id, name, ciphertext, nonce, created_by, created_at, updated_at FROM pipeline_secrets
WHERE project_id = $1 AND repo_id IS NULL AND environment_id IS NULL
ORDER BY name
`

func (q *Queries) ListProjectSecrets(ctx context.Context, projectID uuid.UUID) ([]PipelineSecret, error) {
	rows, err := q.db.Query(ctx, listProjectSecrets, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PipelineSecret{}
	for rows.Next() {
		var i PipelineSecret
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.RepoID,
			&i.EnvironmentID,
			&i.Name,
			&i.Ciphertext,
			&i.Nonce,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepoSecrets = `-- name: ListRepoSecrets :many
SELECT id, project_id, repo_id, environment_id, name, ciphertext, nonce, created_by, created_at, updated_at FROM pipeline_secrets
WHERE repo_id = $1
ORDER BY name
`

func (q *Queries) ListRepoSecrets(ctx context.Context, repoID uuid.NullUUID) ([]PipelineSecret, error) {
	rows, err := q.db.Query(ctx, listRepoSecrets, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PipelineSecret{}
	for rows.Next() {
		var i PipelineSecret
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.RepoID,
			&i.EnvironmentID,
			&i.Name,
			&i.Ciphertext,
			&i.Nonce,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePipelineSecretValue = `-- name: UpdatePipelineSecretValue :one
UPDATE pipeline_secrets
SET ciphertext = $2,
    nonce = $3
WHERE id = $1
RETURNING id, project_id, repo_id, environment_id, name, ciphertext, nonce, created_by, created_at, updated_at
`

type UpdatePipelineSecretValueParams struct {
	ID         uuid.UUID `json:"id"`
	Ciphertext []byte    `json:"ciphertext"`
	Nonce      []byte    `json:"nonce"`
}

func (q *Queries) UpdatePipelineSecretValue(ctx context.Context, arg UpdatePipelineSecretValueParams) (PipelineSecret, error) {
	row := q.db.QueryRow(ctx, updatePipelineSecretValue, arg.ID, arg.Ciphertext, arg.Nonce)
	var i PipelineSecret
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RepoID,
		&i.EnvironmentID,
		&i.Name,
		&i.Ciphertext,
		&i.Nonce,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
