// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pipelines.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPipelineJob = `-- name: CreatePipelineJob :one
INSERT INTO pipeline_jobs (
  run_id, job_key, name, runs_on, status, position, started_at, finished_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, run_id, job_key, name, runs_on, status, position, started_at, finished_at, created_at, updated_at
`

type CreatePipelineJobParams struct {
	RunID      uuid.UUID          `json:"runId"`
	JobKey     string             `json:"jobKey"`
	Name       string             `json:"name"`
	RunsOn     string             `json:"runsOn"`
	Status     string             `json:"status"`
	Position   int32              `json:"position"`
	StartedAt  pgtype.Timestamptz `json:"startedAt"`
	FinishedAt pgtype.Timestamptz `json:"finishedAt"`
}

func (q *Queries) CreatePipelineJob(ctx context.Context, arg CreatePipelineJobParams) (PipelineJob, error) {
	row := q.db.QueryRow(ctx, createPipelineJob,
		arg.RunID,
		arg.JobKey,
		arg.Name,
		arg.RunsOn,
		arg.Status,
		arg.Position,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var i PipelineJob
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.JobKey,
		&i.Name,
		&i.RunsOn,
		&i.Status,
		&i.Position,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPipelineRun = `-- name: CreatePipelineRun :one
INSERT INTO pipeline_runs (
  pipeline_id, run_number, status, event, ref, commit_sha, triggered_by, started_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, pipeline_id, run_number, status, event, ref, commit_sha, triggered_by, started_at, finished_at, created_at, updated_at
`

type CreatePipelineRunParams struct {
	PipelineID  uuid.UUID          `json:"pipelineId"`
	RunNumber   int64              `json:"runNumber"`
	Status      string             `json:"status"`
	Event       string             `json:"event"`
	Ref         string             `json:"ref"`
	CommitSha   string             `json:"commitSha"`
	TriggeredBy uuid.NullUUID      `json:"triggeredBy"`
	StartedAt   pgtype.Timestamptz `json:"startedAt"`
}

func (q *Queries) CreatePipelineRun(ctx context.Context, arg CreatePipelineRunParams) (PipelineRun, error) {
	row := q.db.QueryRow(ctx, createPipelineRun,
		arg.PipelineID,
		arg.RunNumber,
		arg.Status,
		arg.Event,
		arg.Ref,
		arg.CommitSha,
		arg.TriggeredBy,
		arg.StartedAt,
	)
	var i PipelineRun
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.RunNumber,
		&i.Status,
		&i.Event,
		&i.Ref,
		&i.CommitSha,
		&i.TriggeredBy,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPipelineStep = `-- name: CreatePipelineStep :one
INSERT INTO pipeline_steps (
  job_id, position, name, step_type, status, logs, started_at, finished_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, job_id, position, name, step_type, status, logs, started_at, finished_at, created_at, updated_at
`

type CreatePipelineStepParams struct {
	JobID      uuid.UUID          `json:"jobId"`
	Position   int32              `json:"position"`
	Name       string             `json:"name"`
	StepType   string             `json:"stepType"`
	Status     string             `json:"status"`
	Logs       string             `json:"logs"`
	StartedAt  pgtype.Timestamptz `json:"startedAt"`
	FinishedAt pgtype.Timestamptz `json:"finishedAt"`
}

func (q *Queries) CreatePipelineStep(ctx context.Context, arg CreatePipelineStepParams) (PipelineStep, error) {
	row := q.db.QueryRow(ctx, createPipelineStep,
		arg.JobID,
		arg.Position,
		arg.Name,
		arg.StepType,
		arg.Status,
		arg.Logs,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var i PipelineStep
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Position,
		&i.Name,
		&i.StepType,
		&i.Status,
		&i.Logs,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPipeline = `-- name: GetPipeline :one
SELECT id, repo_id, workflow_path, name, created_at, updated_at FROM pipelines
WHERE id = $1
`

func (q *Queries) GetPipeline(ctx context.Context, id uuid.UUID) (Pipeline, error) {
	row := q.db.QueryRow(ctx, getPipeline, id)
	var i Pipeline
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.WorkflowPath,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPipelineByPath = `-- name: GetPipelineByPath :one
SELECT id, repo_id, workflow_path, name, created_at, updated_at FROM pipelines
WHERE repo_id = $1 AND workflow_path = $2
`

type GetPipelineByPathParams struct {
	RepoID       uuid.UUID `json:"repoId"`
	WorkflowPath string    `json:"workflowPath"`
}

func (q *Queries) GetPipelineByPath(ctx context.Context, arg GetPipelineByPathParams) (Pipeline, error) {
	row := q.db.QueryRow(ctx, getPipelineByPath, arg.RepoID, arg.WorkflowPath)
	var i Pipeline
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.WorkflowPath,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPipelineRun = `-- name: GetPipelineRun :one
SELECT id, pipeline_id, run_number, status, event, ref, commit_sha, triggered_by, started_at, finished_at, created_at, updated_at FROM pipeline_runs
WHERE id = $1
`

func (q *Queries) GetPipelineRun(ctx context.Context, id uuid.UUID) (PipelineRun, error) {
	row := q.db.QueryRow(ctx, getPipelineRun, id)
	var i PipelineRun
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.RunNumber,
		&i.Status,
		&i.Event,
		&i.Ref,
		&i.CommitSha,
		&i.TriggeredBy,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPipelineRunByNumber = `-- name: GetPipelineRunByNumber :one
SELECT id, pipeline_id, run_number, status, event, ref, commit_sha, triggered_by, started_at, finished_at, created_at, updated_at FROM pipeline_runs
WHERE pipeline_id = $1 AND run_number = $2
`

type GetPipelineRunByNumberParams struct {
	PipelineID uuid.UUID `json:"pipelineId"`
	RunNumber  int64     `json:"runNumber"`
}

func (q *Queries) GetPipelineRunByNumber(ctx context.Context, arg GetPipelineRunByNumberParams) (PipelineRun, error) {
	row := q.db.QueryRow(ctx, getPipelineRunByNumber, arg.PipelineID, arg.RunNumber)
	var i PipelineRun
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.RunNumber,
		&i.Status,
		&i.Event,
		&i.Ref,
		&i.CommitSha,
		&i.TriggeredBy,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJobsByRun = `-- name: ListJobsByRun :many
SELECT id, run_id, job_key, name, runs_on, status, position, started_at, finished_at, created_at, updated_at FROM pipeline_jobs
WHERE run_id = $1
ORDER BY position
`

func (q *Queries) ListJobsByRun(ctx context.Context, runID uuid.UUID) ([]PipelineJob, error) {
	rows, err := q.db.Query(ctx, listJobsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PipelineJob{}
	for rows.Next() {
		var i PipelineJob
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.JobKey,
			&i.Name,
			&i.RunsOn,
			&i.Status,
			&i.Position,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPipelinesByRepo = `-- name: ListPipelinesByRepo :many
SELECT id, repo_id, workflow_path, name, created_at, updated_at FROM pipelines
WHERE repo_id = $1
ORDER BY workflow_path
`

func (q *Queries) ListPipelinesByRepo(ctx context.Context, repoID uuid.UUID) ([]Pipeline, error) {
	rows, err := q.db.Query(ctx, listPipelinesByRepo, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Pipeline{}
	for rows.Next() {
		var i Pipeline
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.WorkflowPath,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsByPipeline = `-- name: ListRunsByPipeline :many
SELECT id, pipeline_id, run_number, status, event, ref, commit_sha, triggered_by, started_at, finished_at, created_at, updated_at FROM pipeline_runs
WHERE pipeline_id = $1
ORDER BY run_number DESC
LIMIT $2
`

type ListRunsByPipelineParams struct {
	PipelineID uuid.UUID `json:"pipelineId"`
	Limit      int32     `json:"limit"`
}

func (q *Queries) ListRunsByPipeline(ctx context.Context, arg ListRunsByPipelineParams) ([]PipelineRun, error) {
	rows, err := q.db.Query(ctx, listRunsByPipeline, arg.PipelineID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PipelineRun{}
	for rows.Next() {
		var i PipelineRun
		if err := rows.Scan(
			&i.ID,
			&i.PipelineID,
			&i.RunNumber,
			&i.Status,
			&i.Event,
			&i.Ref,
			&i.CommitSha,
			&i.TriggeredBy,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsByRepo = `-- name: ListRunsByRepo :many
SELECT r.id, r.pipeline_id, r.run_number, r.status, r.event, r.ref, r.commit_sha, r.triggered_by, r.started_at, r.finished_at, r.created_at, r.updated_at FROM pipeline_runs r
JOIN pipelines p ON p.id = r.pipeline_id
WHERE p.repo_id = $1
ORDER BY r.created_at DESC
LIMIT $2
`

type ListRunsByRepoParams struct {
	RepoID uuid.UUID `json:"repoId"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) ListRunsByRepo(ctx context.Context, arg ListRunsByRepoParams) ([]PipelineRun, error) {
	rows, err := q.db.Query(ctx, listRunsByRepo, arg.RepoID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PipelineRun{}
	for rows.Next() {
		var i PipelineRun
		if err := rows.Scan(
			&i.ID,
			&i.PipelineID,
			&i.RunNumber,
			&i.Status,
			&i.Event,
			&i.Ref,
			&i.CommitSha,
			&i.TriggeredBy,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStepsByJob = `-- name: ListStepsByJob :many
SELECT id, job_id, position, name, step_type, status, logs, started_at, finished_at, created_at, updated_at FROM pipeline_steps
WHERE job_id = $1
ORDER BY position
`

func (q *Queries) ListStepsByJob(ctx context.Context, jobID uuid.UUID) ([]PipelineStep, error) {
	rows, err := q.db.Query(ctx, listStepsByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PipelineStep{}
	for rows.Next() {
		var i PipelineStep
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Position,
			&i.Name,
			&i.StepType,
			&i.Status,
			&i.Logs,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextRunNumber = `-- name: NextRunNumber :one
SELECT COALESCE(MAX(run_number), 0) + 1 AS next
FROM pipeline_runs
WHERE pipeline_id = $1
`

func (q *Queries) NextRunNumber(ctx context.Context, pipelineID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextRunNumber, pipelineID)
	var next int32
	err := row.Scan(&next)
	return next, err
}

const updatePipelineRunStatus = `-- name: UpdatePipelineRunStatus :one
UPDATE pipeline_runs
SET status = $2, finished_at = $3
WHERE id = $1
RETURNING id, pipeline_id, run_number, status, event, ref, commit_sha, triggered_by, started_at, finished_at, created_at, updated_at
`

type UpdatePipelineRunStatusParams struct {
	ID         uuid.UUID          `json:"id"`
	Status     string             `json:"status"`
	FinishedAt pgtype.Timestamptz `json:"finishedAt"`
}

func (q *Queries) UpdatePipelineRunStatus(ctx context.Context, arg UpdatePipelineRunStatusParams) (PipelineRun, error) {
	row := q.db.QueryRow(ctx, updatePipelineRunStatus, arg.ID, arg.Status, arg.FinishedAt)
	var i PipelineRun
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.RunNumber,
		&i.Status,
		&i.Event,
		&i.Ref,
		&i.CommitSha,
		&i.TriggeredBy,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPipeline = `-- name: UpsertPipeline :one
INSERT INTO pipelines (repo_id, workflow_path, name)
VALUES ($1, $2, $3)
ON CONFLICT (repo_id, workflow_path) DO UPDATE SET
  name = EXCLUDED.name
RETURNING id, repo_id, workflow_path, name, created_at, updated_at
`

type UpsertPipelineParams struct {
	RepoID       uuid.UUID `json:"repoId"`
	WorkflowPath string    `json:"workflowPath"`
	Name         string    `json:"name"`
}

func (q *Queries) UpsertPipeline(ctx context.Context, arg UpsertPipelineParams) (Pipeline, error) {
	row := q.db.QueryRow(ctx, upsertPipeline, arg.RepoID, arg.WorkflowPath, arg.Name)
	var i Pipeline
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.WorkflowPath,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
