// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: policies.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deletePoliciesByScope = `-- name: DeletePoliciesByScope :execrows
DELETE FROM policies
WHERE scope_type = $1 AND scope_id = $2
`

type DeletePoliciesByScopeParams struct {
	ScopeType string    `json:"scopeType"`
	ScopeID   uuid.UUID `json:"scopeId"`
}

// Remove all policies attached to a scope (used when the scope is deleted, since
// scope_id is polymorphic and cannot cascade via a foreign key).
func (q *Queries) DeletePoliciesByScope(ctx context.Context, arg DeletePoliciesByScopeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePoliciesByScope, arg.ScopeType, arg.ScopeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePolicy = `-- name: DeletePolicy :execrows
DELETE FROM policies
WHERE scope_type = $1 AND scope_id = $2 AND kind = $3 AND selector = $4
`

type DeletePolicyParams struct {
	ScopeType string    `json:"scopeType"`
	ScopeID   uuid.UUID `json:"scopeId"`
	Kind      string    `json:"kind"`
	Selector  string    `json:"selector"`
}

func (q *Queries) DeletePolicy(ctx context.Context, arg DeletePolicyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePolicy,
		arg.ScopeType,
		arg.ScopeID,
		arg.Kind,
		arg.Selector,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listEffectivePolicies = `-- name: ListEffectivePolicies :many
SELECT id, scope_type, scope_id, kind, selector, rules, locked, enabled, created_at, updated_at FROM policies
WHERE enabled
  AND kind = $1
  AND (
    (scope_type = 'repo' AND scope_id = $2)
    OR (scope_type = 'project' AND scope_id = $3)
    OR (scope_type = 'tenant' AND scope_id = $4)
  )
ORDER BY CASE scope_type WHEN 'tenant' THEN 0 WHEN 'project' THEN 1 ELSE 2 END, selector
`

type ListEffectivePoliciesParams struct {
	Kind      string    `json:"kind"`
	ScopeID   uuid.UUID `json:"scopeId"`
	ScopeID_2 uuid.UUID `json:"scopeId2"`
	ScopeID_3 uuid.UUID `json:"scopeId3"`
}

// Every enabled policy of a kind across the scopes governing a repo: the repo
// itself, its project, and that project's tenant. Ordered broad -> narrow so the
// resolver can fold tenant onto project onto repo.
func (q *Queries) ListEffectivePolicies(ctx context.Context, arg ListEffectivePoliciesParams) ([]Policy, error) {
	rows, err := q.db.Query(ctx, listEffectivePolicies,
		arg.Kind,
		arg.ScopeID,
		arg.ScopeID_2,
		arg.ScopeID_3,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Policy{}
	for rows.Next() {
		var i Policy
		if err := rows.Scan(
			&i.ID,
			&i.ScopeType,
			&i.ScopeID,
			&i.Kind,
			&i.Selector,
			&i.Rules,
			&i.Locked,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPoliciesByScope = `-- name: ListPoliciesByScope :many
SELECT id, scope_type, scope_id, kind, selector, rules, locked, enabled, created_at, updated_at FROM policies
WHERE scope_type = $1 AND scope_id = $2 AND kind = $3
ORDER BY selector
`

type ListPoliciesByScopeParams struct {
	ScopeType string    `json:"scopeType"`
	ScopeID   uuid.UUID `json:"scopeId"`
	Kind      string    `json:"kind"`
}

// Policies declared directly at one scope for a kind (e.g. a repo's own branch
// policies). Used to render and edit what a scope owns, before inheritance.
func (q *Queries) ListPoliciesByScope(ctx context.Context, arg ListPoliciesByScopeParams) ([]Policy, error) {
	rows, err := q.db.Query(ctx, listPoliciesByScope, arg.ScopeType, arg.ScopeID, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Policy{}
	for rows.Next() {
		var i Policy
		if err := rows.Scan(
			&i.ID,
			&i.ScopeType,
			&i.ScopeID,
			&i.Kind,
			&i.Selector,
			&i.Rules,
			&i.Locked,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPolicy = `-- name: UpsertPolicy :one
INSERT INTO policies (scope_type, scope_id, kind, selector, rules, locked, enabled)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (scope_type, scope_id, kind, selector) DO UPDATE SET
  rules   = EXCLUDED.rules,
  locked  = EXCLUDED.locked,
  enabled = EXCLUDED.enabled
RETURNING id, scope_type, scope_id, kind, selector, rules, locked, enabled, created_at, updated_at
`

type UpsertPolicyParams struct {
	ScopeType string    `json:"scopeType"`
	ScopeID   uuid.UUID `json:"scopeId"`
	Kind      string    `json:"kind"`
	Selector  string    `json:"selector"`
	Rules     []byte    `json:"rules"`
	Locked    bool      `json:"locked"`
	Enabled   bool      `json:"enabled"`
}

func (q *Queries) UpsertPolicy(ctx context.Context, arg UpsertPolicyParams) (Policy, error) {
	row := q.db.QueryRow(ctx, upsertPolicy,
		arg.ScopeType,
		arg.ScopeID,
		arg.Kind,
		arg.Selector,
		arg.Rules,
		arg.Locked,
		arg.Enabled,
	)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.ScopeType,
		&i.ScopeID,
		&i.Kind,
		&i.Selector,
		&i.Rules,
		&i.Locked,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
