// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_sync_outbox.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countProjectSyncEventsByProject = `-- name: CountProjectSyncEventsByProject :one
SELECT count(*) FROM project_sync_outbox WHERE project_id = $1
`

func (q *Queries) CountProjectSyncEventsByProject(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectSyncEventsByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertProjectSyncEvent = `-- name: InsertProjectSyncEvent :one
INSERT INTO project_sync_outbox (id, project_id, event_type, payload, occurred_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, event_type, payload, occurred_at, attempts, next_attempt_at, delivered_at
`

type InsertProjectSyncEventParams struct {
	ID         uuid.UUID `json:"id"`
	ProjectID  uuid.UUID `json:"projectId"`
	EventType  string    `json:"eventType"`
	Payload    []byte    `json:"payload"`
	OccurredAt time.Time `json:"occurredAt"`
}

// Enqueue a project-mirror event. The caller supplies the event id and
// occurred_at explicitly so they match the values embedded in the JSON payload
// (Tempo dedupes intake on the event id). Called inside the same transaction as
// the project mutation.
func (q *Queries) InsertProjectSyncEvent(ctx context.Context, arg InsertProjectSyncEventParams) (ProjectSyncOutbox, error) {
	row := q.db.QueryRow(ctx, insertProjectSyncEvent,
		arg.ID,
		arg.ProjectID,
		arg.EventType,
		arg.Payload,
		arg.OccurredAt,
	)
	var i ProjectSyncOutbox
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EventType,
		&i.Payload,
		&i.OccurredAt,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.DeliveredAt,
	)
	return i, err
}

const listPendingProjectSyncEvents = `-- name: ListPendingProjectSyncEvents :many
SELECT id, project_id, event_type, payload, occurred_at, attempts, next_attempt_at, delivered_at FROM project_sync_outbox
WHERE delivered_at IS NULL AND next_attempt_at <= now()
ORDER BY occurred_at
LIMIT $1
`

// Undelivered events that are due for a delivery attempt, oldest first.
func (q *Queries) ListPendingProjectSyncEvents(ctx context.Context, limit int32) ([]ProjectSyncOutbox, error) {
	rows, err := q.db.Query(ctx, listPendingProjectSyncEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectSyncOutbox{}
	for rows.Next() {
		var i ProjectSyncOutbox
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EventType,
			&i.Payload,
			&i.OccurredAt,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsWithTenant = `-- name: ListProjectsWithTenant :many
SELECT p.id, p.slug, p.name, p.is_personal, t.slug AS tenant_slug
FROM projects p
JOIN tenants t ON t.id = p.tenant_id
ORDER BY p.created_at
`

type ListProjectsWithTenantRow struct {
	ID         uuid.UUID `json:"id"`
	Slug       string    `json:"slug"`
	Name       string    `json:"name"`
	IsPersonal bool      `json:"isPersonal"`
	TenantSlug string    `json:"tenantSlug"`
}

// Every project with its tenant slug, for the one-shot backfill.
func (q *Queries) ListProjectsWithTenant(ctx context.Context) ([]ListProjectsWithTenantRow, error) {
	rows, err := q.db.Query(ctx, listProjectsWithTenant)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsWithTenantRow{}
	for rows.Next() {
		var i ListProjectsWithTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.IsPersonal,
			&i.TenantSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markProjectSyncEventDelivered = `-- name: MarkProjectSyncEventDelivered :exec
UPDATE project_sync_outbox
SET delivered_at = now()
WHERE id = $1
`

func (q *Queries) MarkProjectSyncEventDelivered(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markProjectSyncEventDelivered, id)
	return err
}

const markProjectSyncEventFailed = `-- name: MarkProjectSyncEventFailed :exec
UPDATE project_sync_outbox
SET attempts = attempts + 1, next_attempt_at = $2
WHERE id = $1
`

type MarkProjectSyncEventFailedParams struct {
	ID            uuid.UUID `json:"id"`
	NextAttemptAt time.Time `json:"nextAttemptAt"`
}

// Record a failed delivery attempt and schedule the next one.
func (q *Queries) MarkProjectSyncEventFailed(ctx context.Context, arg MarkProjectSyncEventFailedParams) error {
	_, err := q.db.Exec(ctx, markProjectSyncEventFailed, arg.ID, arg.NextAttemptAt)
	return err
}
