// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countProjects = `-- name: CountProjects :one
SELECT count(*) FROM projects
`

func (q *Queries) CountProjects(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProjects)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (tenant_id, slug, name, description, is_personal)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, slug, name, description, forgejo_org_name, is_personal, created_at, updated_at
`

type CreateProjectParams struct {
	TenantID    uuid.UUID `json:"tenantId"`
	Slug        string    `json:"slug"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	IsPersonal  bool      `json:"isPersonal"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.TenantID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.IsPersonal,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.ForgejoOrgName,
		&i.IsPersonal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, tenant_id, slug, name, description, forgejo_org_name, is_personal, created_at, updated_at FROM projects WHERE id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.ForgejoOrgName,
		&i.IsPersonal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectBySlug = `-- name: GetProjectBySlug :one
SELECT id, tenant_id, slug, name, description, forgejo_org_name, is_personal, created_at, updated_at FROM projects WHERE lower(slug) = lower($1)
`

func (q *Queries) GetProjectBySlug(ctx context.Context, lower string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectBySlug, lower)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.ForgejoOrgName,
		&i.IsPersonal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, tenant_id, slug, name, description, forgejo_org_name, is_personal, created_at, updated_at FROM projects
ORDER BY slug
LIMIT $1 OFFSET $2
`

type ListProjectsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.ForgejoOrgName,
			&i.IsPersonal,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByUser = `-- name: ListProjectsByUser :many
SELECT p.id, p.tenant_id, p.slug, p.name, p.description, p.forgejo_org_name, p.is_personal, p.created_at, p.updated_at, m.role AS member_role
FROM project_members m
JOIN projects p ON p.id = m.project_id
WHERE m.user_id = $1
ORDER BY p.slug
`

type ListProjectsByUserRow struct {
	ID             uuid.UUID   `json:"id"`
	TenantID       uuid.UUID   `json:"tenantId"`
	Slug           string      `json:"slug"`
	Name           string      `json:"name"`
	Description    string      `json:"description"`
	ForgejoOrgName pgtype.Text `json:"forgejoOrgName"`
	IsPersonal     bool        `json:"isPersonal"`
	CreatedAt      time.Time   `json:"createdAt"`
	UpdatedAt      time.Time   `json:"updatedAt"`
	MemberRole     string      `json:"memberRole"`
}

func (q *Queries) ListProjectsByUser(ctx context.Context, userID uuid.UUID) ([]ListProjectsByUserRow, error) {
	rows, err := q.db.Query(ctx, listProjectsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsByUserRow{}
	for rows.Next() {
		var i ListProjectsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.ForgejoOrgName,
			&i.IsPersonal,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MemberRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProjectForgejoName = `-- name: SetProjectForgejoName :one
UPDATE projects
SET forgejo_org_name = $2
WHERE id = $1
RETURNING id, tenant_id, slug, name, description, forgejo_org_name, is_personal, created_at, updated_at
`

type SetProjectForgejoNameParams struct {
	ID             uuid.UUID   `json:"id"`
	ForgejoOrgName pgtype.Text `json:"forgejoOrgName"`
}

func (q *Queries) SetProjectForgejoName(ctx context.Context, arg SetProjectForgejoNameParams) (Project, error) {
	row := q.db.QueryRow(ctx, setProjectForgejoName, arg.ID, arg.ForgejoOrgName)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.ForgejoOrgName,
		&i.IsPersonal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
