// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddProjectMember(ctx context.Context, arg AddProjectMemberParams) error
	CountProjects(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAuthIdentity(ctx context.Context, arg CreateAuthIdentityParams) (AuthIdentity, error)
	CreateGitToken(ctx context.Context, arg CreateGitTokenParams) (GitToken, error)
	CreatePipelineJob(ctx context.Context, arg CreatePipelineJobParams) (PipelineJob, error)
	CreatePipelineRun(ctx context.Context, arg CreatePipelineRunParams) (PipelineRun, error)
	CreatePipelineStep(ctx context.Context, arg CreatePipelineStepParams) (PipelineStep, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateRepository(ctx context.Context, arg CreateRepositoryParams) (Repository, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteBranchPolicy(ctx context.Context, arg DeleteBranchPolicyParams) (int64, error)
	DeleteGitToken(ctx context.Context, arg DeleteGitTokenParams) error
	DeleteRepository(ctx context.Context, id uuid.UUID) error
	GetAuthIdentity(ctx context.Context, arg GetAuthIdentityParams) (AuthIdentity, error)
	GetBranchPolicy(ctx context.Context, arg GetBranchPolicyParams) (BranchPolicy, error)
	GetGitToken(ctx context.Context, arg GetGitTokenParams) (GitToken, error)
	GetPipeline(ctx context.Context, id uuid.UUID) (Pipeline, error)
	GetPipelineByPath(ctx context.Context, arg GetPipelineByPathParams) (Pipeline, error)
	GetPipelineRun(ctx context.Context, id uuid.UUID) (PipelineRun, error)
	GetPipelineRunByNumber(ctx context.Context, arg GetPipelineRunByNumberParams) (PipelineRun, error)
	GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error)
	GetProjectBySlug(ctx context.Context, lower string) (Project, error)
	GetRepositoryByID(ctx context.Context, id uuid.UUID) (Repository, error)
	GetRepositoryBySlug(ctx context.Context, arg GetRepositoryBySlugParams) (Repository, error)
	GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error)
	GetTenantBySlug(ctx context.Context, lower string) (Tenant, error)
	GetUserByEmail(ctx context.Context, lower string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, lower string) (User, error)
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error)
	ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]AuditLog, error)
	ListAuthIdentitiesForUser(ctx context.Context, userID uuid.UUID) ([]AuthIdentity, error)
	ListBranchPoliciesByRepo(ctx context.Context, repoID uuid.UUID) ([]BranchPolicy, error)
	ListGitTokensByUser(ctx context.Context, userID uuid.UUID) ([]GitToken, error)
	ListJobsByRun(ctx context.Context, runID uuid.UUID) ([]PipelineJob, error)
	ListPipelinesByRepo(ctx context.Context, repoID uuid.UUID) ([]Pipeline, error)
	ListProjectMembers(ctx context.Context, projectID uuid.UUID) ([]ListProjectMembersRow, error)
	ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error)
	ListProjectsByUser(ctx context.Context, userID uuid.UUID) ([]ListProjectsByUserRow, error)
	ListRepositoriesByProject(ctx context.Context, arg ListRepositoriesByProjectParams) ([]Repository, error)
	ListRunsByPipeline(ctx context.Context, arg ListRunsByPipelineParams) ([]PipelineRun, error)
	ListRunsByRepo(ctx context.Context, arg ListRunsByRepoParams) ([]PipelineRun, error)
	ListStepsByJob(ctx context.Context, jobID uuid.UUID) ([]PipelineStep, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	NextRunNumber(ctx context.Context, pipelineID uuid.UUID) (int32, error)
	RemoveProjectMember(ctx context.Context, arg RemoveProjectMemberParams) error
	SetProjectForgejoName(ctx context.Context, arg SetProjectForgejoNameParams) (Project, error)
	SetRepositoryArchived(ctx context.Context, arg SetRepositoryArchivedParams) (Repository, error)
	SetRepositoryForgejoLink(ctx context.Context, arg SetRepositoryForgejoLinkParams) (Repository, error)
	SetUserForgejoLink(ctx context.Context, arg SetUserForgejoLinkParams) (User, error)
	UpdateAuthIdentitySecret(ctx context.Context, arg UpdateAuthIdentitySecretParams) error
	UpdatePipelineRunStatus(ctx context.Context, arg UpdatePipelineRunStatusParams) (PipelineRun, error)
	UpdateRepository(ctx context.Context, arg UpdateRepositoryParams) (Repository, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpsertBranchPolicy(ctx context.Context, arg UpsertBranchPolicyParams) (BranchPolicy, error)
	UpsertPipeline(ctx context.Context, arg UpsertPipelineParams) (Pipeline, error)
}

var _ Querier = (*Queries)(nil)
