// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddOrgMember(ctx context.Context, arg AddOrgMemberParams) error
	AddTeamMember(ctx context.Context, arg AddTeamMemberParams) error
	CountOrganizations(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAuthIdentity(ctx context.Context, arg CreateAuthIdentityParams) (AuthIdentity, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateRepository(ctx context.Context, arg CreateRepositoryParams) (Repository, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteBranchPolicy(ctx context.Context, arg DeleteBranchPolicyParams) (int64, error)
	DeleteRepository(ctx context.Context, id uuid.UUID) error
	GetAuthIdentity(ctx context.Context, arg GetAuthIdentityParams) (AuthIdentity, error)
	GetBranchPolicy(ctx context.Context, arg GetBranchPolicyParams) (BranchPolicy, error)
	GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error)
	GetOrganizationBySlug(ctx context.Context, lower string) (Organization, error)
	GetRepositoryByID(ctx context.Context, id uuid.UUID) (Repository, error)
	GetRepositoryBySlug(ctx context.Context, arg GetRepositoryBySlugParams) (Repository, error)
	GetTeamByID(ctx context.Context, id uuid.UUID) (Team, error)
	GetTeamBySlug(ctx context.Context, arg GetTeamBySlugParams) (Team, error)
	GetUserByEmail(ctx context.Context, lower string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, lower string) (User, error)
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error)
	ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]AuditLog, error)
	ListAuthIdentitiesForUser(ctx context.Context, userID uuid.UUID) ([]AuthIdentity, error)
	ListBranchPoliciesByRepo(ctx context.Context, repoID uuid.UUID) ([]BranchPolicy, error)
	ListOrgMembers(ctx context.Context, orgID uuid.UUID) ([]ListOrgMembersRow, error)
	ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]Organization, error)
	ListRepositoriesByOrg(ctx context.Context, arg ListRepositoriesByOrgParams) ([]Repository, error)
	ListRepositoriesByTeam(ctx context.Context, owningTeamID uuid.UUID) ([]Repository, error)
	ListTeamMembers(ctx context.Context, teamID uuid.UUID) ([]ListTeamMembersRow, error)
	ListTeamsByOrg(ctx context.Context, orgID uuid.UUID) ([]Team, error)
	ListTeamsByUser(ctx context.Context, userID uuid.UUID) ([]ListTeamsByUserRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	RemoveOrgMember(ctx context.Context, arg RemoveOrgMemberParams) error
	RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error
	SetOrganizationForgejoName(ctx context.Context, arg SetOrganizationForgejoNameParams) (Organization, error)
	SetRepositoryArchived(ctx context.Context, arg SetRepositoryArchivedParams) (Repository, error)
	SetRepositoryForgejoLink(ctx context.Context, arg SetRepositoryForgejoLinkParams) (Repository, error)
	SetUserForgejoLink(ctx context.Context, arg SetUserForgejoLinkParams) (User, error)
	UpdateAuthIdentitySecret(ctx context.Context, arg UpdateAuthIdentitySecretParams) error
	UpdateRepository(ctx context.Context, arg UpdateRepositoryParams) (Repository, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpsertBranchPolicy(ctx context.Context, arg UpsertBranchPolicyParams) (BranchPolicy, error)
}

var _ Querier = (*Queries)(nil)
