// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddOrgMember(ctx context.Context, arg AddOrgMemberParams) error
	AddTeamMember(ctx context.Context, arg AddTeamMemberParams) error
	CountOrganizations(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAuthIdentity(ctx context.Context, arg CreateAuthIdentityParams) (AuthIdentity, error)
	CreateGitToken(ctx context.Context, arg CreateGitTokenParams) (GitToken, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreatePipelineJob(ctx context.Context, arg CreatePipelineJobParams) (PipelineJob, error)
	CreatePipelineRun(ctx context.Context, arg CreatePipelineRunParams) (PipelineRun, error)
	CreatePipelineStep(ctx context.Context, arg CreatePipelineStepParams) (PipelineStep, error)
	CreateRepository(ctx context.Context, arg CreateRepositoryParams) (Repository, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteBranchPolicy(ctx context.Context, arg DeleteBranchPolicyParams) (int64, error)
	DeleteGitToken(ctx context.Context, arg DeleteGitTokenParams) error
	DeleteRepository(ctx context.Context, id uuid.UUID) error
	GetAuthIdentity(ctx context.Context, arg GetAuthIdentityParams) (AuthIdentity, error)
	GetBranchPolicy(ctx context.Context, arg GetBranchPolicyParams) (BranchPolicy, error)
	GetGitToken(ctx context.Context, arg GetGitTokenParams) (GitToken, error)
	GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error)
	GetOrganizationBySlug(ctx context.Context, lower string) (Organization, error)
	GetPipeline(ctx context.Context, id uuid.UUID) (Pipeline, error)
	GetPipelineByPath(ctx context.Context, arg GetPipelineByPathParams) (Pipeline, error)
	GetPipelineRun(ctx context.Context, id uuid.UUID) (PipelineRun, error)
	GetPipelineRunByNumber(ctx context.Context, arg GetPipelineRunByNumberParams) (PipelineRun, error)
	GetRepositoryByID(ctx context.Context, id uuid.UUID) (Repository, error)
	GetRepositoryBySlug(ctx context.Context, arg GetRepositoryBySlugParams) (Repository, error)
	GetTeamByID(ctx context.Context, id uuid.UUID) (Team, error)
	GetTeamBySlug(ctx context.Context, arg GetTeamBySlugParams) (Team, error)
	GetUserByEmail(ctx context.Context, lower string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, lower string) (User, error)
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error)
	ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]AuditLog, error)
	ListAuthIdentitiesForUser(ctx context.Context, userID uuid.UUID) ([]AuthIdentity, error)
	ListBranchPoliciesByRepo(ctx context.Context, repoID uuid.UUID) ([]BranchPolicy, error)
	ListGitTokensByUser(ctx context.Context, userID uuid.UUID) ([]GitToken, error)
	ListJobsByRun(ctx context.Context, runID uuid.UUID) ([]PipelineJob, error)
	ListOrgMembers(ctx context.Context, orgID uuid.UUID) ([]ListOrgMembersRow, error)
	ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]Organization, error)
	ListPipelinesByRepo(ctx context.Context, repoID uuid.UUID) ([]Pipeline, error)
	ListRepositoriesByOrg(ctx context.Context, arg ListRepositoriesByOrgParams) ([]Repository, error)
	ListRepositoriesByTeam(ctx context.Context, owningTeamID uuid.UUID) ([]Repository, error)
	ListRunsByPipeline(ctx context.Context, arg ListRunsByPipelineParams) ([]PipelineRun, error)
	ListRunsByRepo(ctx context.Context, arg ListRunsByRepoParams) ([]PipelineRun, error)
	ListStepsByJob(ctx context.Context, jobID uuid.UUID) ([]PipelineStep, error)
	ListTeamMembers(ctx context.Context, teamID uuid.UUID) ([]ListTeamMembersRow, error)
	ListTeamsByOrg(ctx context.Context, orgID uuid.UUID) ([]Team, error)
	ListTeamsByUser(ctx context.Context, userID uuid.UUID) ([]ListTeamsByUserRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	NextRunNumber(ctx context.Context, pipelineID uuid.UUID) (int32, error)
	RemoveOrgMember(ctx context.Context, arg RemoveOrgMemberParams) error
	RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error
	SetOrganizationForgejoName(ctx context.Context, arg SetOrganizationForgejoNameParams) (Organization, error)
	SetRepositoryArchived(ctx context.Context, arg SetRepositoryArchivedParams) (Repository, error)
	SetRepositoryForgejoLink(ctx context.Context, arg SetRepositoryForgejoLinkParams) (Repository, error)
	SetUserForgejoLink(ctx context.Context, arg SetUserForgejoLinkParams) (User, error)
	UpdateAuthIdentitySecret(ctx context.Context, arg UpdateAuthIdentitySecretParams) error
	UpdatePipelineRunStatus(ctx context.Context, arg UpdatePipelineRunStatusParams) (PipelineRun, error)
	UpdateRepository(ctx context.Context, arg UpdateRepositoryParams) (Repository, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpsertBranchPolicy(ctx context.Context, arg UpsertBranchPolicyParams) (BranchPolicy, error)
	UpsertPipeline(ctx context.Context, arg UpsertPipelineParams) (Pipeline, error)
}

var _ Querier = (*Queries)(nil)
