// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repo_stars.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type RepoStar struct {
	UserID    uuid.UUID `json:"userId"`
	RepoID    uuid.UUID `json:"repoId"`
	CreatedAt time.Time `json:"createdAt"`
}

type StarRepoParams struct {
	UserID uuid.UUID `json:"userId"`
	RepoID uuid.UUID `json:"repoId"`
}

const starRepo = `-- name: StarRepo :exec
INSERT INTO repo_stars (user_id, repo_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

func (q *Queries) StarRepo(ctx context.Context, arg StarRepoParams) error {
	_, err := q.db.Exec(ctx, starRepo, arg.UserID, arg.RepoID)
	return err
}

type UnstarRepoParams struct {
	UserID uuid.UUID `json:"userId"`
	RepoID uuid.UUID `json:"repoId"`
}

const unstarRepo = `-- name: UnstarRepo :exec
DELETE FROM repo_stars
WHERE user_id = $1 AND repo_id = $2
`

func (q *Queries) UnstarRepo(ctx context.Context, arg UnstarRepoParams) error {
	_, err := q.db.Exec(ctx, unstarRepo, arg.UserID, arg.RepoID)
	return err
}

type GetRepoStarParams struct {
	UserID uuid.UUID `json:"userId"`
	RepoID uuid.UUID `json:"repoId"`
}

const getRepoStar = `-- name: GetRepoStar :one
SELECT user_id, repo_id, created_at FROM repo_stars
WHERE user_id = $1 AND repo_id = $2
`

func (q *Queries) GetRepoStar(ctx context.Context, arg GetRepoStarParams) (RepoStar, error) {
	row := q.db.QueryRow(ctx, getRepoStar, arg.UserID, arg.RepoID)
	var i RepoStar
	err := row.Scan(&i.UserID, &i.RepoID, &i.CreatedAt)
	return i, err
}

const countRepoStars = `-- name: CountRepoStars :one
SELECT COUNT(*) FROM repo_stars
WHERE repo_id = $1
`

func (q *Queries) CountRepoStars(ctx context.Context, repoID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRepoStars, repoID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
