// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repositories.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRepository = `-- name: CreateRepository :one
INSERT INTO repositories (
  org_id, owning_team_id, slug, name, description, visibility, default_branch
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, org_id, owning_team_id, slug, name, description, visibility, default_branch, is_archived, forgejo_repo_id, forgejo_owner, forgejo_name, created_at, updated_at
`

type CreateRepositoryParams struct {
	OrgID         uuid.UUID `json:"orgId"`
	OwningTeamID  uuid.UUID `json:"owningTeamId"`
	Slug          string    `json:"slug"`
	Name          string    `json:"name"`
	Description   string    `json:"description"`
	Visibility    string    `json:"visibility"`
	DefaultBranch string    `json:"defaultBranch"`
}

func (q *Queries) CreateRepository(ctx context.Context, arg CreateRepositoryParams) (Repository, error) {
	row := q.db.QueryRow(ctx, createRepository,
		arg.OrgID,
		arg.OwningTeamID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Visibility,
		arg.DefaultBranch,
	)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.OwningTeamID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.DefaultBranch,
		&i.IsArchived,
		&i.ForgejoRepoID,
		&i.ForgejoOwner,
		&i.ForgejoName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepositoryByID = `-- name: GetRepositoryByID :one
SELECT id, org_id, owning_team_id, slug, name, description, visibility, default_branch, is_archived, forgejo_repo_id, forgejo_owner, forgejo_name, created_at, updated_at FROM repositories WHERE id = $1
`

func (q *Queries) GetRepositoryByID(ctx context.Context, id uuid.UUID) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepositoryByID, id)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.OwningTeamID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.DefaultBranch,
		&i.IsArchived,
		&i.ForgejoRepoID,
		&i.ForgejoOwner,
		&i.ForgejoName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepositoryBySlug = `-- name: GetRepositoryBySlug :one
SELECT id, org_id, owning_team_id, slug, name, description, visibility, default_branch, is_archived, forgejo_repo_id, forgejo_owner, forgejo_name, created_at, updated_at FROM repositories
WHERE org_id = $1 AND lower(slug) = lower($2)
`

type GetRepositoryBySlugParams struct {
	OrgID uuid.UUID `json:"orgId"`
	Lower string    `json:"lower"`
}

func (q *Queries) GetRepositoryBySlug(ctx context.Context, arg GetRepositoryBySlugParams) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepositoryBySlug, arg.OrgID, arg.Lower)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.OwningTeamID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.DefaultBranch,
		&i.IsArchived,
		&i.ForgejoRepoID,
		&i.ForgejoOwner,
		&i.ForgejoName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRepositoriesByOrg = `-- name: ListRepositoriesByOrg :many
SELECT id, org_id, owning_team_id, slug, name, description, visibility, default_branch, is_archived, forgejo_repo_id, forgejo_owner, forgejo_name, created_at, updated_at FROM repositories
WHERE org_id = $1
ORDER BY slug
LIMIT $2 OFFSET $3
`

type ListRepositoriesByOrgParams struct {
	OrgID  uuid.UUID `json:"orgId"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListRepositoriesByOrg(ctx context.Context, arg ListRepositoriesByOrgParams) ([]Repository, error) {
	rows, err := q.db.Query(ctx, listRepositoriesByOrg, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Repository{}
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.OwningTeamID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Visibility,
			&i.DefaultBranch,
			&i.IsArchived,
			&i.ForgejoRepoID,
			&i.ForgejoOwner,
			&i.ForgejoName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepositoriesByTeam = `-- name: ListRepositoriesByTeam :many
SELECT id, org_id, owning_team_id, slug, name, description, visibility, default_branch, is_archived, forgejo_repo_id, forgejo_owner, forgejo_name, created_at, updated_at FROM repositories
WHERE owning_team_id = $1
ORDER BY slug
`

func (q *Queries) ListRepositoriesByTeam(ctx context.Context, owningTeamID uuid.UUID) ([]Repository, error) {
	rows, err := q.db.Query(ctx, listRepositoriesByTeam, owningTeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Repository{}
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.OwningTeamID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Visibility,
			&i.DefaultBranch,
			&i.IsArchived,
			&i.ForgejoRepoID,
			&i.ForgejoOwner,
			&i.ForgejoName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRepositoryArchived = `-- name: SetRepositoryArchived :one
UPDATE repositories
SET is_archived = $2
WHERE id = $1
RETURNING id, org_id, owning_team_id, slug, name, description, visibility, default_branch, is_archived, forgejo_repo_id, forgejo_owner, forgejo_name, created_at, updated_at
`

type SetRepositoryArchivedParams struct {
	ID         uuid.UUID `json:"id"`
	IsArchived bool      `json:"isArchived"`
}

func (q *Queries) SetRepositoryArchived(ctx context.Context, arg SetRepositoryArchivedParams) (Repository, error) {
	row := q.db.QueryRow(ctx, setRepositoryArchived, arg.ID, arg.IsArchived)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.OwningTeamID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.DefaultBranch,
		&i.IsArchived,
		&i.ForgejoRepoID,
		&i.ForgejoOwner,
		&i.ForgejoName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setRepositoryForgejoLink = `-- name: SetRepositoryForgejoLink :one
UPDATE repositories
SET forgejo_repo_id = $2, forgejo_owner = $3, forgejo_name = $4
WHERE id = $1
RETURNING id, org_id, owning_team_id, slug, name, description, visibility, default_branch, is_archived, forgejo_repo_id, forgejo_owner, forgejo_name, created_at, updated_at
`

type SetRepositoryForgejoLinkParams struct {
	ID            uuid.UUID   `json:"id"`
	ForgejoRepoID pgtype.Int8 `json:"forgejoRepoId"`
	ForgejoOwner  pgtype.Text `json:"forgejoOwner"`
	ForgejoName   pgtype.Text `json:"forgejoName"`
}

func (q *Queries) SetRepositoryForgejoLink(ctx context.Context, arg SetRepositoryForgejoLinkParams) (Repository, error) {
	row := q.db.QueryRow(ctx, setRepositoryForgejoLink,
		arg.ID,
		arg.ForgejoRepoID,
		arg.ForgejoOwner,
		arg.ForgejoName,
	)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.OwningTeamID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.DefaultBranch,
		&i.IsArchived,
		&i.ForgejoRepoID,
		&i.ForgejoOwner,
		&i.ForgejoName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
