// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (org_id, slug, name, description)
VALUES ($1, $2, $3, $4)
RETURNING id, org_id, slug, name, description, created_at, updated_at
`

type CreateTeamParams struct {
	OrgID       uuid.UUID `json:"orgId"`
	Slug        string    `json:"slug"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam,
		arg.OrgID,
		arg.Slug,
		arg.Name,
		arg.Description,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, org_id, slug, name, description, created_at, updated_at FROM teams WHERE id = $1
`

func (q *Queries) GetTeamByID(ctx context.Context, id uuid.UUID) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByID, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamBySlug = `-- name: GetTeamBySlug :one
SELECT id, org_id, slug, name, description, created_at, updated_at FROM teams
WHERE org_id = $1 AND lower(slug) = lower($2)
`

type GetTeamBySlugParams struct {
	OrgID uuid.UUID `json:"orgId"`
	Lower string    `json:"lower"`
}

func (q *Queries) GetTeamBySlug(ctx context.Context, arg GetTeamBySlugParams) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamBySlug, arg.OrgID, arg.Lower)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTeamsByOrg = `-- name: ListTeamsByOrg :many
SELECT id, org_id, slug, name, description, created_at, updated_at FROM teams
WHERE org_id = $1
ORDER BY slug
`

func (q *Queries) ListTeamsByOrg(ctx context.Context, orgID uuid.UUID) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeamsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
