// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant_members.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addTenantMember = `-- name: AddTenantMember :exec
INSERT INTO tenant_members (tenant_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (tenant_id, user_id) DO UPDATE SET role = EXCLUDED.role
`

type AddTenantMemberParams struct {
	TenantID uuid.UUID `json:"tenantId"`
	UserID   uuid.UUID `json:"userId"`
	Role     string    `json:"role"`
}

func (q *Queries) AddTenantMember(ctx context.Context, arg AddTenantMemberParams) error {
	_, err := q.db.Exec(ctx, addTenantMember, arg.TenantID, arg.UserID, arg.Role)
	return err
}

const getTenantMember = `-- name: GetTenantMember :one
SELECT tenant_id, user_id, role, created_at FROM tenant_members
WHERE tenant_id = $1 AND user_id = $2
`

type GetTenantMemberParams struct {
	TenantID uuid.UUID `json:"tenantId"`
	UserID   uuid.UUID `json:"userId"`
}

func (q *Queries) GetTenantMember(ctx context.Context, arg GetTenantMemberParams) (TenantMember, error) {
	row := q.db.QueryRow(ctx, getTenantMember, arg.TenantID, arg.UserID)
	var i TenantMember
	err := row.Scan(
		&i.TenantID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listTenantMembers = `-- name: ListTenantMembers :many
SELECT u.id, u.username, u.email, u.display_name, u.is_admin,
       m.role AS member_role, m.created_at AS member_since
FROM tenant_members m
JOIN users u ON u.id = m.user_id
WHERE m.tenant_id = $1
ORDER BY u.username
`

type ListTenantMembersRow struct {
	ID          uuid.UUID `json:"id"`
	Username    string    `json:"username"`
	Email       string    `json:"email"`
	DisplayName string    `json:"displayName"`
	IsAdmin     bool      `json:"isAdmin"`
	MemberRole  string    `json:"memberRole"`
	MemberSince time.Time `json:"memberSince"`
}

func (q *Queries) ListTenantMembers(ctx context.Context, tenantID uuid.UUID) ([]ListTenantMembersRow, error) {
	rows, err := q.db.Query(ctx, listTenantMembers, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantMembersRow{}
	for rows.Next() {
		var i ListTenantMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.DisplayName,
			&i.IsAdmin,
			&i.MemberRole,
			&i.MemberSince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTenantMember = `-- name: RemoveTenantMember :exec
DELETE FROM tenant_members WHERE tenant_id = $1 AND user_id = $2
`

type RemoveTenantMemberParams struct {
	TenantID uuid.UUID `json:"tenantId"`
	UserID   uuid.UUID `json:"userId"`
}

func (q *Queries) RemoveTenantMember(ctx context.Context, arg RemoveTenantMemberParams) error {
	_, err := q.db.Exec(ctx, removeTenantMember, arg.TenantID, arg.UserID)
	return err
}

const countTenantAdmins = `-- name: CountTenantAdmins :one
SELECT count(*) FROM tenant_members WHERE tenant_id = $1 AND role = 'admin'
`

func (q *Queries) CountTenantAdmins(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTenantAdmins, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
