// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant_members.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addTenantMember = `-- name: AddTenantMember :exec
INSERT INTO tenant_members (tenant_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (tenant_id, user_id) DO UPDATE SET role = EXCLUDED.role
`

type AddTenantMemberParams struct {
	TenantID uuid.UUID `json:"tenantId"`
	UserID   uuid.UUID `json:"userId"`
	Role     string    `json:"role"`
}

func (q *Queries) AddTenantMember(ctx context.Context, arg AddTenantMemberParams) error {
	_, err := q.db.Exec(ctx, addTenantMember, arg.TenantID, arg.UserID, arg.Role)
	return err
}

const getTenantMember = `-- name: GetTenantMember :one
SELECT tenant_id, user_id, role, created_at FROM tenant_members
WHERE tenant_id = $1 AND user_id = $2
`

type GetTenantMemberParams struct {
	TenantID uuid.UUID `json:"tenantId"`
	UserID   uuid.UUID `json:"userId"`
}

func (q *Queries) GetTenantMember(ctx context.Context, arg GetTenantMemberParams) (TenantMember, error) {
	row := q.db.QueryRow(ctx, getTenantMember, arg.TenantID, arg.UserID)
	var i TenantMember
	err := row.Scan(
		&i.TenantID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
