// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant_admin_seeds.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addTenantAdminSeed = `-- name: AddTenantAdminSeed :exec
INSERT INTO tenant_admin_seeds (tenant_id, email) VALUES ($1, lower($2))
ON CONFLICT (tenant_id, email) DO NOTHING
`

type AddTenantAdminSeedParams struct {
	TenantID uuid.UUID `json:"tenantId"`
	Email    string    `json:"email"`
}

func (q *Queries) AddTenantAdminSeed(ctx context.Context, arg AddTenantAdminSeedParams) error {
	_, err := q.db.Exec(ctx, addTenantAdminSeed, arg.TenantID, arg.Email)
	return err
}

const isTenantAdminSeeded = `-- name: IsTenantAdminSeeded :one
SELECT EXISTS(SELECT 1 FROM tenant_admin_seeds WHERE tenant_id = $1 AND email = lower($2))
`

type IsTenantAdminSeededParams struct {
	TenantID uuid.UUID `json:"tenantId"`
	Email    string    `json:"email"`
}

func (q *Queries) IsTenantAdminSeeded(ctx context.Context, arg IsTenantAdminSeededParams) (bool, error) {
	row := q.db.QueryRow(ctx, isTenantAdminSeeded, arg.TenantID, arg.Email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
