// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant_sso.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getTenantSSO = `-- name: GetTenantSSO :one
SELECT tenant_id, protocol, issuer, client_id, client_secret_ciphertext, client_secret_nonce, email_domain, enabled, created_at, updated_at
FROM tenant_sso_config WHERE tenant_id = $1
`

func (q *Queries) GetTenantSSO(ctx context.Context, tenantID uuid.UUID) (TenantSsoConfig, error) {
	row := q.db.QueryRow(ctx, getTenantSSO, tenantID)
	var i TenantSsoConfig
	err := row.Scan(
		&i.TenantID,
		&i.Protocol,
		&i.Issuer,
		&i.ClientID,
		&i.ClientSecretCiphertext,
		&i.ClientSecretNonce,
		&i.EmailDomain,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTenantSSO = `-- name: UpsertTenantSSO :one
INSERT INTO tenant_sso_config (
  tenant_id, protocol, issuer, client_id, client_secret_ciphertext, client_secret_nonce, email_domain, enabled
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (tenant_id) DO UPDATE SET
  protocol = EXCLUDED.protocol,
  issuer = EXCLUDED.issuer,
  client_id = EXCLUDED.client_id,
  client_secret_ciphertext = EXCLUDED.client_secret_ciphertext,
  client_secret_nonce = EXCLUDED.client_secret_nonce,
  email_domain = EXCLUDED.email_domain,
  enabled = EXCLUDED.enabled
RETURNING tenant_id, protocol, issuer, client_id, client_secret_ciphertext, client_secret_nonce, email_domain, enabled, created_at, updated_at
`

type UpsertTenantSSOParams struct {
	TenantID               uuid.UUID `json:"tenantId"`
	Protocol               string    `json:"protocol"`
	Issuer                 string    `json:"issuer"`
	ClientID               string    `json:"clientId"`
	ClientSecretCiphertext []byte    `json:"clientSecretCiphertext"`
	ClientSecretNonce      []byte    `json:"clientSecretNonce"`
	EmailDomain            string    `json:"emailDomain"`
	Enabled                bool      `json:"enabled"`
}

func (q *Queries) UpsertTenantSSO(ctx context.Context, arg UpsertTenantSSOParams) (TenantSsoConfig, error) {
	row := q.db.QueryRow(ctx, upsertTenantSSO,
		arg.TenantID,
		arg.Protocol,
		arg.Issuer,
		arg.ClientID,
		arg.ClientSecretCiphertext,
		arg.ClientSecretNonce,
		arg.EmailDomain,
		arg.Enabled,
	)
	var i TenantSsoConfig
	err := row.Scan(
		&i.TenantID,
		&i.Protocol,
		&i.Issuer,
		&i.ClientID,
		&i.ClientSecretCiphertext,
		&i.ClientSecretNonce,
		&i.EmailDomain,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTenantSSO = `-- name: DeleteTenantSSO :exec
DELETE FROM tenant_sso_config WHERE tenant_id = $1
`

func (q *Queries) DeleteTenantSSO(ctx context.Context, tenantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTenantSSO, tenantID)
	return err
}
