// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, display_name, is_admin, is_active)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, username, email, display_name, is_admin, is_active, forgejo_user_id, forgejo_username, created_at, updated_at
`

type CreateUserParams struct {
	Username    string `json:"username"`
	Email       string `json:"email"`
	DisplayName string `json:"displayName"`
	IsAdmin     bool   `json:"isAdmin"`
	IsActive    bool   `json:"isActive"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.DisplayName,
		arg.IsAdmin,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.IsAdmin,
		&i.IsActive,
		&i.ForgejoUserID,
		&i.ForgejoUsername,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, display_name, is_admin, is_active, forgejo_user_id, forgejo_username, created_at, updated_at FROM users WHERE lower(email) = lower($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.IsAdmin,
		&i.IsActive,
		&i.ForgejoUserID,
		&i.ForgejoUsername,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, display_name, is_admin, is_active, forgejo_user_id, forgejo_username, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.IsAdmin,
		&i.IsActive,
		&i.ForgejoUserID,
		&i.ForgejoUsername,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, display_name, is_admin, is_active, forgejo_user_id, forgejo_username, created_at, updated_at FROM users WHERE lower(username) = lower($1)
`

func (q *Queries) GetUserByUsername(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.IsAdmin,
		&i.IsActive,
		&i.ForgejoUserID,
		&i.ForgejoUsername,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, display_name, is_admin, is_active, forgejo_user_id, forgejo_username, created_at, updated_at FROM users
ORDER BY username
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.DisplayName,
			&i.IsAdmin,
			&i.IsActive,
			&i.ForgejoUserID,
			&i.ForgejoUsername,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserForgejoLink = `-- name: SetUserForgejoLink :one
UPDATE users
SET forgejo_user_id = $2, forgejo_username = $3
WHERE id = $1
RETURNING id, username, email, display_name, is_admin, is_active, forgejo_user_id, forgejo_username, created_at, updated_at
`

type SetUserForgejoLinkParams struct {
	ID              uuid.UUID   `json:"id"`
	ForgejoUserID   pgtype.Int8 `json:"forgejoUserId"`
	ForgejoUsername pgtype.Text `json:"forgejoUsername"`
}

func (q *Queries) SetUserForgejoLink(ctx context.Context, arg SetUserForgejoLinkParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserForgejoLink, arg.ID, arg.ForgejoUserID, arg.ForgejoUsername)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.IsAdmin,
		&i.IsActive,
		&i.ForgejoUserID,
		&i.ForgejoUsername,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
