// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: work_item_ref_outbox.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertWorkItemRefEvent = `-- name: InsertWorkItemRefEvent :one
INSERT INTO work_item_ref_outbox (id, project_id, payload, occurred_at)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, payload, occurred_at, attempts, next_attempt_at, delivered_at
`

type InsertWorkItemRefEventParams struct {
	ID         uuid.UUID `json:"id"`
	ProjectID  uuid.UUID `json:"projectId"`
	Payload    []byte    `json:"payload"`
	OccurredAt time.Time `json:"occurredAt"`
}

// Enqueue a work-item-refs push. The caller supplies the row id and occurred_at
// explicitly so they match the values used by the dispatcher's logs and any
// future dedupe. Called from the Forgejo webhook handler after scanning a
// push/pull_request for work-item keys.
func (q *Queries) InsertWorkItemRefEvent(ctx context.Context, arg InsertWorkItemRefEventParams) (WorkItemRefOutbox, error) {
	row := q.db.QueryRow(ctx, insertWorkItemRefEvent,
		arg.ID,
		arg.ProjectID,
		arg.Payload,
		arg.OccurredAt,
	)
	var i WorkItemRefOutbox
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Payload,
		&i.OccurredAt,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.DeliveredAt,
	)
	return i, err
}

const listPendingWorkItemRefEvents = `-- name: ListPendingWorkItemRefEvents :many
SELECT id, project_id, payload, occurred_at, attempts, next_attempt_at, delivered_at FROM work_item_ref_outbox
WHERE delivered_at IS NULL AND next_attempt_at <= now()
ORDER BY occurred_at
LIMIT $1
`

// Undelivered pushes that are due for a delivery attempt, oldest first.
func (q *Queries) ListPendingWorkItemRefEvents(ctx context.Context, limit int32) ([]WorkItemRefOutbox, error) {
	rows, err := q.db.Query(ctx, listPendingWorkItemRefEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkItemRefOutbox{}
	for rows.Next() {
		var i WorkItemRefOutbox
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Payload,
			&i.OccurredAt,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWorkItemRefEventDelivered = `-- name: MarkWorkItemRefEventDelivered :exec
UPDATE work_item_ref_outbox
SET delivered_at = now()
WHERE id = $1
`

func (q *Queries) MarkWorkItemRefEventDelivered(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markWorkItemRefEventDelivered, id)
	return err
}

const markWorkItemRefEventFailed = `-- name: MarkWorkItemRefEventFailed :exec
UPDATE work_item_ref_outbox
SET attempts = attempts + 1, next_attempt_at = $2
WHERE id = $1
`

type MarkWorkItemRefEventFailedParams struct {
	ID            uuid.UUID `json:"id"`
	NextAttemptAt time.Time `json:"nextAttemptAt"`
}

// Record a failed delivery attempt and schedule the next one.
func (q *Queries) MarkWorkItemRefEventFailed(ctx context.Context, arg MarkWorkItemRefEventFailedParams) error {
	_, err := q.db.Exec(ctx, markWorkItemRefEventFailed, arg.ID, arg.NextAttemptAt)
	return err
}
